-- Revertir Migración Fase 2: Catálogo y Media

DROP TABLE IF EXISTS movie_genres CASCADE;
DROP TABLE IF EXISTS movie_countries CASCADE;
DROP TABLE IF EXISTS serie_genres CASCADE;
DROP TABLE IF EXISTS serie_countries CASCADE;
DROP TABLE IF EXISTS serie_episodes CASCADE;
DROP TABLE IF EXISTS serie_seasons CASCADE;
DROP TABLE IF EXISTS series CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS casts CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS networks CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
