DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS tutorials CASCADE;
DROP TABLE IF EXISTS downloads CASCADE;

DROP TABLE IF EXISTS trivia_sessions CASCADE;
DROP TABLE IF EXISTS trivia_questions CASCADE;
DROP TABLE IF EXISTS daily_missions CASCADE;
DROP TABLE IF EXISTS user_achievements CASCADE;
DROP TABLE IF EXISTS achievements CASCADE;
DROP TABLE IF EXISTS arcade_user_stats CASCADE;
DROP TABLE IF EXISTS arcade_game_settings CASCADE;

DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS content_requests CASCADE;

DROP TABLE IF EXISTS profile_views CASCADE;
DROP TABLE IF EXISTS watch_progress CASCADE;
DROP TABLE IF EXISTS watch_later CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
