DROP TABLE IF EXISTS event_providers CASCADE;
DROP TABLE IF EXISTS iptv_playlists CASCADE;
DROP TABLE IF EXISTS livetv_categories CASCADE;
DROP TABLE IF EXISTS livetv_videos CASCADE;
DROP TABLE IF EXISTS livetvs CASCADE;

DROP TABLE IF EXISTS media_playback_sessions CASCADE;
DROP TABLE IF EXISTS media_subtitle_tracks CASCADE;
DROP TABLE IF EXISTS media_audio_tracks CASCADE;
DROP TABLE IF EXISTS media_sources CASCADE;
DROP TABLE IF EXISTS providers CASCADE;

DROP TABLE IF EXISTS media_images CASCADE;
DROP TABLE IF EXISTS serie_networks CASCADE;
DROP TABLE IF EXISTS serie_countries CASCADE;
DROP TABLE IF EXISTS serie_genres CASCADE;
DROP TABLE IF EXISTS movie_networks CASCADE;
DROP TABLE IF EXISTS movie_countries CASCADE;
DROP TABLE IF EXISTS movie_genres CASCADE;
DROP TABLE IF EXISTS serie_cast CASCADE;
DROP TABLE IF EXISTS movie_cast CASCADE;

DROP TABLE IF EXISTS serie_episodes CASCADE;
DROP TABLE IF EXISTS serie_seasons CASCADE;
DROP TABLE IF EXISTS series CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS casts CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS networks CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
