DROP TABLE IF EXISTS scraper_run_failures CASCADE;
DROP TABLE IF EXISTS scraper_runs CASCADE;
DROP TABLE IF EXISTS scraper_sources CASCADE;
DROP TABLE IF EXISTS curator_media CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS app_settings CASCADE;
