// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const createAdminRole = `-- name: CreateAdminRole :one
INSERT INTO roles (name, description, is_system) 
VALUES ($1, $2, false)
RETURNING id, name, description, is_system, created_at
`

type CreateAdminRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type CreateAdminRoleRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAdminRole(ctx context.Context, arg CreateAdminRoleParams) (CreateAdminRoleRow, error) {
	row := q.db.QueryRow(ctx, createAdminRole, arg.Name, arg.Description)
	var i CreateAdminRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminStaff = `-- name: CreateAdminStaff :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email
`

type CreateAdminStaffParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateAdminStaffRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateAdminStaff(ctx context.Context, arg CreateAdminStaffParams) (CreateAdminStaffRow, error) {
	row := q.db.QueryRow(ctx, createAdminStaff, arg.Name, arg.Email, arg.PasswordHash)
	var i CreateAdminStaffRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const createMediaAudioTrack = `-- name: CreateMediaAudioTrack :one
INSERT INTO media_audio_tracks (
  media_source_id, track_no, lang, codec, channel_layout, bitrate_kbps, sample_rate_hz, is_default, title
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, media_source_id, track_no, lang, codec, channel_layout, bitrate_kbps, sample_rate_hz, is_default, title, created_at, updated_at
`

type CreateMediaAudioTrackParams struct {
	MediaSourceID int64       `json:"media_source_id"`
	TrackNo       int16       `json:"track_no"`
	Lang          pgtype.Text `json:"lang"`
	Codec         pgtype.Text `json:"codec"`
	ChannelLayout pgtype.Text `json:"channel_layout"`
	BitrateKbps   pgtype.Int2 `json:"bitrate_kbps"`
	SampleRateHz  pgtype.Int4 `json:"sample_rate_hz"`
	IsDefault     bool        `json:"is_default"`
	Title         pgtype.Text `json:"title"`
}

func (q *Queries) CreateMediaAudioTrack(ctx context.Context, arg CreateMediaAudioTrackParams) (MediaAudioTrack, error) {
	row := q.db.QueryRow(ctx, createMediaAudioTrack,
		arg.MediaSourceID,
		arg.TrackNo,
		arg.Lang,
		arg.Codec,
		arg.ChannelLayout,
		arg.BitrateKbps,
		arg.SampleRateHz,
		arg.IsDefault,
		arg.Title,
	)
	var i MediaAudioTrack
	err := row.Scan(
		&i.ID,
		&i.MediaSourceID,
		&i.TrackNo,
		&i.Lang,
		&i.Codec,
		&i.ChannelLayout,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.IsDefault,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaSource = `-- name: CreateMediaSource :one
INSERT INTO media_sources (
  episode_id, movie_id, label, quality, type, link, link_hash, size_bytes, duration_sec, video_codec, audio_channels, dynamic_range, bit_depth,
  recap_start, recap_end, opening_start, opening_end, ending_start, ending_end
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, provider_id, movie_id, episode_id, label, quality, link, link_hash, size_bytes, duration_sec, video_codec, audio_channels, dynamic_range, bit_depth, recap_start, recap_end, opening_start, opening_end, ending_start, ending_end, status, created_at, updated_at, type
`

type CreateMediaSourceParams struct {
	EpisodeID     pgtype.Int8 `json:"episode_id"`
	MovieID       pgtype.Int8 `json:"movie_id"`
	Label         pgtype.Text `json:"label"`
	Quality       pgtype.Text `json:"quality"`
	Type          string      `json:"type"`
	Link          string      `json:"link"`
	LinkHash      pgtype.Text `json:"link_hash"`
	SizeBytes     pgtype.Int8 `json:"size_bytes"`
	DurationSec   pgtype.Int4 `json:"duration_sec"`
	VideoCodec    pgtype.Text `json:"video_codec"`
	AudioChannels pgtype.Text `json:"audio_channels"`
	DynamicRange  pgtype.Text `json:"dynamic_range"`
	BitDepth      pgtype.Int2 `json:"bit_depth"`
	RecapStart    int32       `json:"recap_start"`
	RecapEnd      int32       `json:"recap_end"`
	OpeningStart  int32       `json:"opening_start"`
	OpeningEnd    int32       `json:"opening_end"`
	EndingStart   int32       `json:"ending_start"`
	EndingEnd     int32       `json:"ending_end"`
}

func (q *Queries) CreateMediaSource(ctx context.Context, arg CreateMediaSourceParams) (MediaSource, error) {
	row := q.db.QueryRow(ctx, createMediaSource,
		arg.EpisodeID,
		arg.MovieID,
		arg.Label,
		arg.Quality,
		arg.Type,
		arg.Link,
		arg.LinkHash,
		arg.SizeBytes,
		arg.DurationSec,
		arg.VideoCodec,
		arg.AudioChannels,
		arg.DynamicRange,
		arg.BitDepth,
		arg.RecapStart,
		arg.RecapEnd,
		arg.OpeningStart,
		arg.OpeningEnd,
		arg.EndingStart,
		arg.EndingEnd,
	)
	var i MediaSource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.MovieID,
		&i.EpisodeID,
		&i.Label,
		&i.Quality,
		&i.Link,
		&i.LinkHash,
		&i.SizeBytes,
		&i.DurationSec,
		&i.VideoCodec,
		&i.AudioChannels,
		&i.DynamicRange,
		&i.BitDepth,
		&i.RecapStart,
		&i.RecapEnd,
		&i.OpeningStart,
		&i.OpeningEnd,
		&i.EndingStart,
		&i.EndingEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const createMediaSubtitleTrack = `-- name: CreateMediaSubtitleTrack :one
INSERT INTO media_subtitle_tracks (
  media_source_id, track_no, lang, type, embedded, link, link_hash, forced, is_default, title
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, media_source_id, track_no, lang, type, embedded, link, link_hash, zip, forced, cc, is_default, title, status, created_at, updated_at
`

type CreateMediaSubtitleTrackParams struct {
	MediaSourceID int64       `json:"media_source_id"`
	TrackNo       int16       `json:"track_no"`
	Lang          pgtype.Text `json:"lang"`
	Type          pgtype.Text `json:"type"`
	Embedded      bool        `json:"embedded"`
	Link          pgtype.Text `json:"link"`
	LinkHash      pgtype.Text `json:"link_hash"`
	Forced        bool        `json:"forced"`
	IsDefault     bool        `json:"is_default"`
	Title         pgtype.Text `json:"title"`
}

func (q *Queries) CreateMediaSubtitleTrack(ctx context.Context, arg CreateMediaSubtitleTrackParams) (MediaSubtitleTrack, error) {
	row := q.db.QueryRow(ctx, createMediaSubtitleTrack,
		arg.MediaSourceID,
		arg.TrackNo,
		arg.Lang,
		arg.Type,
		arg.Embedded,
		arg.Link,
		arg.LinkHash,
		arg.Forced,
		arg.IsDefault,
		arg.Title,
	)
	var i MediaSubtitleTrack
	err := row.Scan(
		&i.ID,
		&i.MediaSourceID,
		&i.TrackNo,
		&i.Lang,
		&i.Type,
		&i.Embedded,
		&i.Link,
		&i.LinkHash,
		&i.Zip,
		&i.Forced,
		&i.Cc,
		&i.IsDefault,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaAudioTrack = `-- name: DeleteMediaAudioTrack :exec
DELETE FROM media_audio_tracks WHERE id = $1
`

func (q *Queries) DeleteMediaAudioTrack(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaAudioTrack, id)
	return err
}

const deleteMediaSource = `-- name: DeleteMediaSource :exec
DELETE FROM media_sources WHERE id = $1
`

func (q *Queries) DeleteMediaSource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaSource, id)
	return err
}

const deleteMediaSubtitleTrack = `-- name: DeleteMediaSubtitleTrack :exec
DELETE FROM media_subtitle_tracks WHERE id = $1
`

func (q *Queries) DeleteMediaSubtitleTrack(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaSubtitleTrack, id)
	return err
}

const getAdminDevicesList = `-- name: GetAdminDevicesList :many
SELECT 
    d.id, d.user_id, u.name as user_name, d.platform, d.device_brand, d.device_model, 
    d.os_version, d.last_ip, d.last_login_at, d.active
FROM devices d
JOIN users u ON d.user_id = u.id
ORDER BY d.last_login_at DESC NULLS LAST
LIMIT 100
`

type GetAdminDevicesListRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	UserName    string             `json:"user_name"`
	Platform    string             `json:"platform"`
	DeviceBrand pgtype.Text        `json:"device_brand"`
	DeviceModel pgtype.Text        `json:"device_model"`
	OsVersion   pgtype.Text        `json:"os_version"`
	LastIp      *netip.Addr        `json:"last_ip"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	Active      bool               `json:"active"`
}

func (q *Queries) GetAdminDevicesList(ctx context.Context) ([]GetAdminDevicesListRow, error) {
	rows, err := q.db.Query(ctx, getAdminDevicesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminDevicesListRow
	for rows.Next() {
		var i GetAdminDevicesListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Platform,
			&i.DeviceBrand,
			&i.DeviceModel,
			&i.OsVersion,
			&i.LastIp,
			&i.LastLoginAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminMoviesList = `-- name: GetAdminMoviesList :many
SELECT 
  id, COALESCE(title_lat, original_name) AS title, release_date, views, active, premium, premiere, upcoming,
  COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'poster' AND is_main = true LIMIT 1), '') AS poster_path
FROM movies
ORDER BY views DESC LIMIT 50
`

type GetAdminMoviesListRow struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	ReleaseDate pgtype.Date `json:"release_date"`
	Views       int64       `json:"views"`
	Active      bool        `json:"active"`
	Premium     bool        `json:"premium"`
	Premiere    bool        `json:"premiere"`
	Upcoming    bool        `json:"upcoming"`
	PosterPath  interface{} `json:"poster_path"`
}

func (q *Queries) GetAdminMoviesList(ctx context.Context) ([]GetAdminMoviesListRow, error) {
	rows, err := q.db.Query(ctx, getAdminMoviesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminMoviesListRow
	for rows.Next() {
		var i GetAdminMoviesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseDate,
			&i.Views,
			&i.Active,
			&i.Premium,
			&i.Premiere,
			&i.Upcoming,
			&i.PosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminRoles = `-- name: GetAdminRoles :many
SELECT id, name, description, is_system, created_at 
FROM roles 
ORDER BY id ASC
`

type GetAdminRolesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminRoles(ctx context.Context) ([]GetAdminRolesRow, error) {
	rows, err := q.db.Query(ctx, getAdminRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminRolesRow
	for rows.Next() {
		var i GetAdminRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminSeriesList = `-- name: GetAdminSeriesList :many
SELECT 
  id, COALESCE(title_lat, original_name) AS title, first_air_date, views, active, premium, premiere, upcoming,
  COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster' AND is_main = true LIMIT 1), '') AS poster_path
FROM series
ORDER BY views DESC LIMIT 50
`

type GetAdminSeriesListRow struct {
	ID           int64       `json:"id"`
	Title        string      `json:"title"`
	FirstAirDate pgtype.Date `json:"first_air_date"`
	Views        int64       `json:"views"`
	Active       bool        `json:"active"`
	Premium      bool        `json:"premium"`
	Premiere     bool        `json:"premiere"`
	Upcoming     bool        `json:"upcoming"`
	PosterPath   interface{} `json:"poster_path"`
}

func (q *Queries) GetAdminSeriesList(ctx context.Context) ([]GetAdminSeriesListRow, error) {
	rows, err := q.db.Query(ctx, getAdminSeriesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminSeriesListRow
	for rows.Next() {
		var i GetAdminSeriesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FirstAirDate,
			&i.Views,
			&i.Active,
			&i.Premium,
			&i.Premiere,
			&i.Upcoming,
			&i.PosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminStaffList = `-- name: GetAdminStaffList :many
SELECT 
    u.id, u.name, u.email, u.is_shadowbanned, u.created_at,
    r.name::text AS primary_role
FROM users u
JOIN user_roles ur ON u.id = ur.user_id
JOIN roles r ON ur.role_id = r.id
WHERE r.name IN ('superadmin', 'admin', 'moderator', 'staff')
ORDER BY u.id DESC LIMIT 50
`

type GetAdminStaffListRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	IsShadowbanned bool               `json:"is_shadowbanned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PrimaryRole    string             `json:"primary_role"`
}

func (q *Queries) GetAdminStaffList(ctx context.Context) ([]GetAdminStaffListRow, error) {
	rows, err := q.db.Query(ctx, getAdminStaffList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminStaffListRow
	for rows.Next() {
		var i GetAdminStaffListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsShadowbanned,
			&i.CreatedAt,
			&i.PrimaryRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT 
  (SELECT count(*) FROM users) as total_users,
  (SELECT count(*) FROM movies) as total_movies,
  (SELECT count(*) FROM devices WHERE active = true) as active_devices
`

type GetAdminStatsRow struct {
	TotalUsers    int64 `json:"total_users"`
	TotalMovies   int64 `json:"total_movies"`
	ActiveDevices int64 `json:"active_devices"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(&i.TotalUsers, &i.TotalMovies, &i.ActiveDevices)
	return i, err
}

const getAdminUsersList = `-- name: GetAdminUsersList :many
SELECT 
    u.id, u.name, u.email, u.is_shadowbanned, u.created_at,
    COALESCE(
        (SELECT r.name FROM user_roles ur JOIN roles r ON ur.role_id = r.id WHERE ur.user_id = u.id LIMIT 1), 
        'Customer'
    )::text AS primary_role
FROM users u
WHERE u.id NOT IN (
    SELECT ur.user_id FROM user_roles ur JOIN roles r ON ur.role_id = r.id WHERE r.name IN ('superadmin', 'admin', 'moderator', 'staff')
)
ORDER BY u.id DESC LIMIT 50
`

type GetAdminUsersListRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	IsShadowbanned bool               `json:"is_shadowbanned"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PrimaryRole    string             `json:"primary_role"`
}

func (q *Queries) GetAdminUsersList(ctx context.Context) ([]GetAdminUsersListRow, error) {
	rows, err := q.db.Query(ctx, getAdminUsersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminUsersListRow
	for rows.Next() {
		var i GetAdminUsersListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsShadowbanned,
			&i.CreatedAt,
			&i.PrimaryRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, name, group_name, description, created_at, updated_at
FROM permissions
ORDER BY group_name ASC, name ASC
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleEpisodeAttribute = `-- name: ToggleEpisodeAttribute :exec
UPDATE serie_episodes SET 
  enable_stream = COALESCE($1, enable_stream),
  enable_download = COALESCE($2, enable_download)
WHERE id = $3
`

type ToggleEpisodeAttributeParams struct {
	EnableStream   pgtype.Bool `json:"enable_stream"`
	EnableDownload pgtype.Bool `json:"enable_download"`
	ID             int64       `json:"id"`
}

func (q *Queries) ToggleEpisodeAttribute(ctx context.Context, arg ToggleEpisodeAttributeParams) error {
	_, err := q.db.Exec(ctx, toggleEpisodeAttribute, arg.EnableStream, arg.EnableDownload, arg.ID)
	return err
}

const toggleMovieAttribute = `-- name: ToggleMovieAttribute :exec
UPDATE movies SET 
  premium = COALESCE($1, premium),
  premiere = COALESCE($2, premiere),
  upcoming = COALESCE($3, upcoming),
  active = COALESCE($4, active)
WHERE id = $5
`

type ToggleMovieAttributeParams struct {
	Premium  pgtype.Bool `json:"premium"`
	Premiere pgtype.Bool `json:"premiere"`
	Upcoming pgtype.Bool `json:"upcoming"`
	Active   pgtype.Bool `json:"active"`
	ID       int64       `json:"id"`
}

func (q *Queries) ToggleMovieAttribute(ctx context.Context, arg ToggleMovieAttributeParams) error {
	_, err := q.db.Exec(ctx, toggleMovieAttribute,
		arg.Premium,
		arg.Premiere,
		arg.Upcoming,
		arg.Active,
		arg.ID,
	)
	return err
}

const toggleSerieAttribute = `-- name: ToggleSerieAttribute :exec
UPDATE series SET 
  premium = COALESCE($1, premium),
  premiere = COALESCE($2, premiere),
  upcoming = COALESCE($3, upcoming),
  active = COALESCE($4, active)
WHERE id = $5
`

type ToggleSerieAttributeParams struct {
	Premium  pgtype.Bool `json:"premium"`
	Premiere pgtype.Bool `json:"premiere"`
	Upcoming pgtype.Bool `json:"upcoming"`
	Active   pgtype.Bool `json:"active"`
	ID       int64       `json:"id"`
}

func (q *Queries) ToggleSerieAttribute(ctx context.Context, arg ToggleSerieAttributeParams) error {
	_, err := q.db.Exec(ctx, toggleSerieAttribute,
		arg.Premium,
		arg.Premiere,
		arg.Upcoming,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateEpisodeMetadata = `-- name: UpdateEpisodeMetadata :one
UPDATE serie_episodes SET 
  name = $2,
  overview = $3,
  air_date = $4,
  still_path = $5
WHERE id = $1 RETURNING id, tmdb_id, tvdb_id, season_id, episode_number, name, overview, still_path, still_path_tv, vote_average, vote_count, views, air_date, enable_stream, enable_download, enable_ads_unlock, created_at, updated_at
`

type UpdateEpisodeMetadataParams struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Overview  pgtype.Text `json:"overview"`
	AirDate   pgtype.Date `json:"air_date"`
	StillPath pgtype.Text `json:"still_path"`
}

func (q *Queries) UpdateEpisodeMetadata(ctx context.Context, arg UpdateEpisodeMetadataParams) (SerieEpisode, error) {
	row := q.db.QueryRow(ctx, updateEpisodeMetadata,
		arg.ID,
		arg.Name,
		arg.Overview,
		arg.AirDate,
		arg.StillPath,
	)
	var i SerieEpisode
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.SeasonID,
		&i.EpisodeNumber,
		&i.Name,
		&i.Overview,
		&i.StillPath,
		&i.StillPathTv,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Views,
		&i.AirDate,
		&i.EnableStream,
		&i.EnableDownload,
		&i.EnableAdsUnlock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPermission = `-- name: UpsertPermission :exec
INSERT INTO permissions (name, group_name, description)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET 
  group_name = excluded.group_name,
  description = excluded.description,
  updated_at = NOW()
`

type UpsertPermissionParams struct {
	Name        string      `json:"name"`
	GroupName   string      `json:"group_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error {
	_, err := q.db.Exec(ctx, upsertPermission, arg.Name, arg.GroupName, arg.Description)
	return err
}
