// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAd = `-- name: CreateAd :one
INSERT INTO ads (
    company, type, content, is_rewarded, reward_tokens, daily_limit, is_active, priority
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, company, type, content, is_rewarded, reward_tokens, daily_limit, is_active, priority, created_at, updated_at
`

type CreateAdParams struct {
	Company      pgtype.Text `json:"company"`
	Type         string      `json:"type"`
	Content      string      `json:"content"`
	IsRewarded   bool        `json:"is_rewarded"`
	RewardTokens int32       `json:"reward_tokens"`
	DailyLimit   int16       `json:"daily_limit"`
	IsActive     bool        `json:"is_active"`
	Priority     int32       `json:"priority"`
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, createAd,
		arg.Company,
		arg.Type,
		arg.Content,
		arg.IsRewarded,
		arg.RewardTokens,
		arg.DailyLimit,
		arg.IsActive,
		arg.Priority,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Type,
		&i.Content,
		&i.IsRewarded,
		&i.RewardTokens,
		&i.DailyLimit,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAd = `-- name: DeleteAd :exec
DELETE FROM ads WHERE id = $1
`

func (q *Queries) DeleteAd(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAd, id)
	return err
}

const getAdByID = `-- name: GetAdByID :one
SELECT id, company, type, content, is_rewarded, reward_tokens, daily_limit, is_active, priority, created_at, updated_at FROM ads WHERE id = $1
`

func (q *Queries) GetAdByID(ctx context.Context, id int64) (Ad, error) {
	row := q.db.QueryRow(ctx, getAdByID, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Type,
		&i.Content,
		&i.IsRewarded,
		&i.RewardTokens,
		&i.DailyLimit,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdView = `-- name: GetAdView :one
SELECT id, user_id, ad_id, views_today, last_view_date, created_at, updated_at FROM user_ad_views
WHERE user_id = $1 AND ad_id = $2
`

type GetAdViewParams struct {
	UserID int64 `json:"user_id"`
	AdID   int64 `json:"ad_id"`
}

func (q *Queries) GetAdView(ctx context.Context, arg GetAdViewParams) (UserAdView, error) {
	row := q.db.QueryRow(ctx, getAdView, arg.UserID, arg.AdID)
	var i UserAdView
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdID,
		&i.ViewsToday,
		&i.LastViewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdsWaterfall = `-- name: GetAdsWaterfall :many
SELECT a.id, a.company, a.type, a.content, a.is_rewarded, a.reward_tokens, a.daily_limit, a.is_active, a.priority, a.created_at, a.updated_at, 
       COALESCE(uav.views_today, 0)::INT as user_views_today
FROM ads a
LEFT JOIN user_ad_views uav 
       ON a.id = uav.ad_id 
      AND uav.user_id = $1 
      AND uav.last_view_date = CURRENT_DATE
WHERE a.is_active = TRUE
  AND (a.daily_limit = 0 OR COALESCE(uav.views_today, 0) < a.daily_limit)
ORDER BY a.priority DESC, a.id ASC
`

type GetAdsWaterfallRow struct {
	ID             int64              `json:"id"`
	Company        pgtype.Text        `json:"company"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	IsRewarded     bool               `json:"is_rewarded"`
	RewardTokens   int32              `json:"reward_tokens"`
	DailyLimit     int16              `json:"daily_limit"`
	IsActive       bool               `json:"is_active"`
	Priority       int32              `json:"priority"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserViewsToday int32              `json:"user_views_today"`
}

// Returns all active ads ordered by priority.
// We LEFT JOIN user_ad_views to check if the user has exceeded their daily limit.
func (q *Queries) GetAdsWaterfall(ctx context.Context, userID int64) ([]GetAdsWaterfallRow, error) {
	rows, err := q.db.Query(ctx, getAdsWaterfall, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdsWaterfallRow
	for rows.Next() {
		var i GetAdsWaterfallRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Type,
			&i.Content,
			&i.IsRewarded,
			&i.RewardTokens,
			&i.DailyLimit,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserViewsToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAds = `-- name: ListAdminAds :many
SELECT id, company, type, content, is_rewarded, reward_tokens, daily_limit, is_active, priority, created_at, updated_at FROM ads
ORDER BY priority DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminAdsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdminAds(ctx context.Context, arg ListAdminAdsParams) ([]Ad, error) {
	rows, err := q.db.Query(ctx, listAdminAds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Type,
			&i.Content,
			&i.IsRewarded,
			&i.RewardTokens,
			&i.DailyLimit,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads
SET 
    company = coalesce($1, company),
    type = coalesce($2, type),
    content = coalesce($3, content),
    is_rewarded = coalesce($4, is_rewarded),
    reward_tokens = coalesce($5, reward_tokens),
    daily_limit = coalesce($6, daily_limit),
    is_active = coalesce($7, is_active),
    priority = coalesce($8, priority),
    updated_at = NOW()
WHERE id = $9
RETURNING id, company, type, content, is_rewarded, reward_tokens, daily_limit, is_active, priority, created_at, updated_at
`

type UpdateAdParams struct {
	Company      pgtype.Text `json:"company"`
	Type         pgtype.Text `json:"type"`
	Content      pgtype.Text `json:"content"`
	IsRewarded   pgtype.Bool `json:"is_rewarded"`
	RewardTokens pgtype.Int4 `json:"reward_tokens"`
	DailyLimit   pgtype.Int2 `json:"daily_limit"`
	IsActive     pgtype.Bool `json:"is_active"`
	Priority     pgtype.Int4 `json:"priority"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, updateAd,
		arg.Company,
		arg.Type,
		arg.Content,
		arg.IsRewarded,
		arg.RewardTokens,
		arg.DailyLimit,
		arg.IsActive,
		arg.Priority,
		arg.ID,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Type,
		&i.Content,
		&i.IsRewarded,
		&i.RewardTokens,
		&i.DailyLimit,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdView = `-- name: UpsertAdView :one
INSERT INTO user_ad_views (
    user_id, ad_id, views_today, last_view_date
) VALUES (
    $1, $2, 1, CURRENT_DATE
)
ON CONFLICT (user_id, ad_id) DO UPDATE 
SET 
    views_today = CASE 
        WHEN user_ad_views.last_view_date = CURRENT_DATE THEN user_ad_views.views_today + 1
        ELSE 1 
    END,
    last_view_date = CURRENT_DATE,
    updated_at = NOW()
RETURNING id, user_id, ad_id, views_today, last_view_date, created_at, updated_at
`

type UpsertAdViewParams struct {
	UserID int64 `json:"user_id"`
	AdID   int64 `json:"ad_id"`
}

func (q *Queries) UpsertAdView(ctx context.Context, arg UpsertAdViewParams) (UserAdView, error) {
	row := q.db.QueryRow(ctx, upsertAdView, arg.UserID, arg.AdID)
	var i UserAdView
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdID,
		&i.ViewsToday,
		&i.LastViewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
