// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE billing.subscriptions
SET status = 'canceled', canceled_at = NOW()
WHERE id = $1 AND user_id = $2
`

type CancelSubscriptionParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error {
	_, err := q.db.Exec(ctx, cancelSubscription, arg.ID, arg.UserID)
	return err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO billing.plans (
    key, category, name, color, priority, badge, is_featured, 
    max_profiles, max_devices, max_pending_requests, parental_control, features
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, key, category, name, color, priority, badge, is_featured, max_profiles, max_devices, max_pending_requests, parental_control, features, is_active, created_at, updated_at, deleted_at
`

type CreatePlanParams struct {
	Key                string      `json:"key"`
	Category           string      `json:"category"`
	Name               string      `json:"name"`
	Color              string      `json:"color"`
	Priority           int16       `json:"priority"`
	Badge              pgtype.Text `json:"badge"`
	IsFeatured         bool        `json:"is_featured"`
	MaxProfiles        int16       `json:"max_profiles"`
	MaxDevices         int16       `json:"max_devices"`
	MaxPendingRequests int16       `json:"max_pending_requests"`
	ParentalControl    bool        `json:"parental_control"`
	Features           []byte      `json:"features"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (BillingPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Key,
		arg.Category,
		arg.Name,
		arg.Color,
		arg.Priority,
		arg.Badge,
		arg.IsFeatured,
		arg.MaxProfiles,
		arg.MaxDevices,
		arg.MaxPendingRequests,
		arg.ParentalControl,
		arg.Features,
	)
	var i BillingPlan
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Category,
		&i.Name,
		&i.Color,
		&i.Priority,
		&i.Badge,
		&i.IsFeatured,
		&i.MaxProfiles,
		&i.MaxDevices,
		&i.MaxPendingRequests,
		&i.ParentalControl,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPlanPrice = `-- name: CreatePlanPrice :one
INSERT INTO billing.plan_prices (
    plan_id, currency, price_cents
) VALUES (
    $1, $2, $3
)
RETURNING id, plan_id, currency, price_cents, created_at, updated_at
`

type CreatePlanPriceParams struct {
	PlanID     int64  `json:"plan_id"`
	Currency   string `json:"currency"`
	PriceCents int32  `json:"price_cents"`
}

func (q *Queries) CreatePlanPrice(ctx context.Context, arg CreatePlanPriceParams) (BillingPlanPrice, error) {
	row := q.db.QueryRow(ctx, createPlanPrice, arg.PlanID, arg.Currency, arg.PriceCents)
	var i BillingPlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Currency,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO billing.subscriptions (
    user_id, plan_id, status, starts_at, renews_at, ends_at, 
    plan_key_snapshot, plan_name_snapshot, currency_paid, price_paid_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, plan_id, status, starts_at, renews_at, ends_at, canceled_at, plan_key_snapshot, plan_name_snapshot, currency_paid, price_paid_cents, meta, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID           pgtype.Int8        `json:"user_id"`
	PlanID           int64              `json:"plan_id"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	RenewsAt         pgtype.Timestamptz `json:"renews_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	PlanKeySnapshot  pgtype.Text        `json:"plan_key_snapshot"`
	PlanNameSnapshot pgtype.Text        `json:"plan_name_snapshot"`
	CurrencyPaid     pgtype.Text        `json:"currency_paid"`
	PricePaidCents   pgtype.Int4        `json:"price_paid_cents"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.StartsAt,
		arg.RenewsAt,
		arg.EndsAt,
		arg.PlanKeySnapshot,
		arg.PlanNameSnapshot,
		arg.CurrencyPaid,
		arg.PricePaidCents,
	)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.RenewsAt,
		&i.EndsAt,
		&i.CanceledAt,
		&i.PlanKeySnapshot,
		&i.PlanNameSnapshot,
		&i.CurrencyPaid,
		&i.PricePaidCents,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserSubscriptions = `-- name: GetActiveUserSubscriptions :many
SELECT s.id, s.user_id, s.plan_id, s.status, s.starts_at, s.renews_at, s.ends_at, s.canceled_at, s.plan_key_snapshot, s.plan_name_snapshot, s.currency_paid, s.price_paid_cents, s.meta, s.created_at, s.updated_at, p.name as plan_name, p.category 
FROM billing.subscriptions s
JOIN billing.plans p ON s.plan_id = p.id
WHERE s.user_id = $1 
  AND s.status = 'active'
  AND (s.ends_at IS NULL OR s.ends_at > NOW())
ORDER BY s.ends_at DESC
`

type GetActiveUserSubscriptionsRow struct {
	ID               int64              `json:"id"`
	UserID           pgtype.Int8        `json:"user_id"`
	PlanID           int64              `json:"plan_id"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	RenewsAt         pgtype.Timestamptz `json:"renews_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	CanceledAt       pgtype.Timestamptz `json:"canceled_at"`
	PlanKeySnapshot  pgtype.Text        `json:"plan_key_snapshot"`
	PlanNameSnapshot pgtype.Text        `json:"plan_name_snapshot"`
	CurrencyPaid     pgtype.Text        `json:"currency_paid"`
	PricePaidCents   pgtype.Int4        `json:"price_paid_cents"`
	Meta             []byte             `json:"meta"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PlanName         string             `json:"plan_name"`
	Category         string             `json:"category"`
}

func (q *Queries) GetActiveUserSubscriptions(ctx context.Context, userID pgtype.Int8) ([]GetActiveUserSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getActiveUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUserSubscriptionsRow
	for rows.Next() {
		var i GetActiveUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartsAt,
			&i.RenewsAt,
			&i.EndsAt,
			&i.CanceledAt,
			&i.PlanKeySnapshot,
			&i.PlanNameSnapshot,
			&i.CurrencyPaid,
			&i.PricePaidCents,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanPrices = `-- name: GetPlanPrices :many
SELECT id, plan_id, currency, price_cents, created_at, updated_at FROM billing.plan_prices
WHERE plan_id = $1
`

func (q *Queries) GetPlanPrices(ctx context.Context, planID int64) ([]BillingPlanPrice, error) {
	rows, err := q.db.Query(ctx, getPlanPrices, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingPlanPrice
	for rows.Next() {
		var i BillingPlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Currency,
			&i.PriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, key, category, name, color, priority, badge, is_featured, max_profiles, max_devices, max_pending_requests, parental_control, features, is_active, created_at, updated_at, deleted_at FROM billing.plans
WHERE is_active = TRUE AND deleted_at IS NULL
ORDER BY priority DESC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]BillingPlan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingPlan
	for rows.Next() {
		var i BillingPlan
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Category,
			&i.Name,
			&i.Color,
			&i.Priority,
			&i.Badge,
			&i.IsFeatured,
			&i.MaxProfiles,
			&i.MaxDevices,
			&i.MaxPendingRequests,
			&i.ParentalControl,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
