// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMovieSlugExists = `-- name: CheckMovieSlugExists :one
SELECT EXISTS(SELECT 1 FROM movies WHERE slug = $1)
`

func (q *Queries) CheckMovieSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, checkMovieSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSerieSlugExists = `-- name: CheckSerieSlugExists :one
SELECT EXISTS(SELECT 1 FROM series WHERE slug = $1)
`

func (q *Queries) CheckSerieSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, checkSerieSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCast = `-- name: CreateCast :one
INSERT INTO casts (name, original_name, gender, place_of_birth, profile_path, imdb_id, known_for_department, biography, adult, birthday, deathday) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, tmdb_id, tvdb_id, uuid, name, original_name, gender, place_of_birth, profile_path, imdb_id, known_for_department, biography, adult, birthday, deathday, views, active, search_vector, created_at, updated_at
`

type CreateCastParams struct {
	Name               string      `json:"name"`
	OriginalName       pgtype.Text `json:"original_name"`
	Gender             pgtype.Int2 `json:"gender"`
	PlaceOfBirth       pgtype.Text `json:"place_of_birth"`
	ProfilePath        pgtype.Text `json:"profile_path"`
	ImdbID             pgtype.Text `json:"imdb_id"`
	KnownForDepartment pgtype.Text `json:"known_for_department"`
	Biography          pgtype.Text `json:"biography"`
	Adult              bool        `json:"adult"`
	Birthday           pgtype.Date `json:"birthday"`
	Deathday           pgtype.Date `json:"deathday"`
}

func (q *Queries) CreateCast(ctx context.Context, arg CreateCastParams) (Cast, error) {
	row := q.db.QueryRow(ctx, createCast,
		arg.Name,
		arg.OriginalName,
		arg.Gender,
		arg.PlaceOfBirth,
		arg.ProfilePath,
		arg.ImdbID,
		arg.KnownForDepartment,
		arg.Biography,
		arg.Adult,
		arg.Birthday,
		arg.Deathday,
	)
	var i Cast
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.Name,
		&i.OriginalName,
		&i.Gender,
		&i.PlaceOfBirth,
		&i.ProfilePath,
		&i.ImdbID,
		&i.KnownForDepartment,
		&i.Biography,
		&i.Adult,
		&i.Birthday,
		&i.Deathday,
		&i.Views,
		&i.Active,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (original_name, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, slug) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, tmdb_id, tvdb_id, uuid, original_name, slug, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, search_vector, created_at, updated_at
`

type CreateCollectionParams struct {
	OriginalName string      `json:"original_name"`
	NameLat      pgtype.Text `json:"name_lat"`
	NameEsp      pgtype.Text `json:"name_esp"`
	NameEng      pgtype.Text `json:"name_eng"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.OriginalName,
		arg.NameLat,
		arg.NameEsp,
		arg.NameEng,
		arg.Overview,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Slug,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.OriginalName,
		&i.Slug,
		&i.NameLat,
		&i.NameEsp,
		&i.NameEng,
		&i.Overview,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (name, english_name, iso_3166_1, logo_path) VALUES ($1, $2, $3, $4) RETURNING id, uuid, name, english_name, iso_3166_1, logo_path, created_at, updated_at
`

type CreateCountryParams struct {
	Name        string      `json:"name"`
	EnglishName pgtype.Text `json:"english_name"`
	Iso31661    string      `json:"iso_3166_1"`
	LogoPath    pgtype.Text `json:"logo_path"`
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Name,
		arg.EnglishName,
		arg.Iso31661,
		arg.LogoPath,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.EnglishName,
		&i.Iso31661,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (name_eng, name_esp, image_path, slug) VALUES ($1, $2, $3, $4) RETURNING id, tmdb_id, tvdb_id, name_eng, name_esp, slug, image_path, created_at, updated_at
`

type CreateGenreParams struct {
	NameEng   string      `json:"name_eng"`
	NameEsp   pgtype.Text `json:"name_esp"`
	ImagePath pgtype.Text `json:"image_path"`
	Slug      string      `json:"slug"`
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre,
		arg.NameEng,
		arg.NameEsp,
		arg.ImagePath,
		arg.Slug,
	)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.NameEng,
		&i.NameEsp,
		&i.Slug,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
    tmdb_id, imdb_id, original_name, title_lat, title_esp, title_eng, 
    overview, release_date, runtime,
    vote_average, vote_count, is_type, active, slug, certification
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, release_date, runtime, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, enable_stream, enable_download, enable_ads_unlock, search_vector, created_at, updated_at
`

type CreateMovieParams struct {
	TmdbID        pgtype.Int8    `json:"tmdb_id"`
	ImdbID        pgtype.Text    `json:"imdb_id"`
	OriginalName  string         `json:"original_name"`
	TitleLat      pgtype.Text    `json:"title_lat"`
	TitleEsp      pgtype.Text    `json:"title_esp"`
	TitleEng      pgtype.Text    `json:"title_eng"`
	Overview      pgtype.Text    `json:"overview"`
	ReleaseDate   pgtype.Date    `json:"release_date"`
	Runtime       pgtype.Int2    `json:"runtime"`
	VoteAverage   pgtype.Numeric `json:"vote_average"`
	VoteCount     int64          `json:"vote_count"`
	IsType        string         `json:"is_type"`
	Active        bool           `json:"active"`
	Slug          string         `json:"slug"`
	Certification pgtype.Text    `json:"certification"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.TmdbID,
		arg.ImdbID,
		arg.OriginalName,
		arg.TitleLat,
		arg.TitleEsp,
		arg.TitleEng,
		arg.Overview,
		arg.ReleaseDate,
		arg.Runtime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.IsType,
		arg.Active,
		arg.Slug,
		arg.Certification,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.TmdbID,
		&i.TvdbID,
		&i.ImdbID,
		&i.IsType,
		&i.OriginalName,
		&i.TitleLat,
		&i.TitleEsp,
		&i.TitleEng,
		&i.Overview,
		&i.TrailerKey,
		&i.ReleaseDate,
		&i.Runtime,
		&i.PosterPath,
		&i.PosterPathTv,
		&i.BackdropPath,
		&i.LogoPath,
		&i.Certification,
		&i.VoteAverage,
		&i.VoteCount,
		&i.VoteGf,
		&i.Views,
		&i.Premiere,
		&i.Upcoming,
		&i.Premium,
		&i.Active,
		&i.EnableStream,
		&i.EnableDownload,
		&i.EnableAdsUnlock,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (name, poster_path, backdrop_path, slug) VALUES ($1, $2, $3, $4) RETURNING id, tmdb_id, tvdb_id, uuid, name, slug, poster_path, backdrop_path, sort_order, created_at, updated_at
`

type CreateNetworkParams struct {
	Name         string      `json:"name"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, createNetwork,
		arg.Name,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Slug,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.Name,
		&i.Slug,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSerie = `-- name: CreateSerie :one
INSERT INTO series (
    tmdb_id, imdb_id, original_name, title_lat, title_esp, title_eng, 
    overview, first_air_date, episode_run_time,
    vote_average, vote_count, is_type, active, slug, certification
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, first_air_date, episode_run_time, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, search_vector, created_at, updated_at
`

type CreateSerieParams struct {
	TmdbID         pgtype.Int8    `json:"tmdb_id"`
	ImdbID         pgtype.Text    `json:"imdb_id"`
	OriginalName   string         `json:"original_name"`
	TitleLat       pgtype.Text    `json:"title_lat"`
	TitleEsp       pgtype.Text    `json:"title_esp"`
	TitleEng       pgtype.Text    `json:"title_eng"`
	Overview       pgtype.Text    `json:"overview"`
	FirstAirDate   pgtype.Date    `json:"first_air_date"`
	EpisodeRunTime pgtype.Int2    `json:"episode_run_time"`
	VoteAverage    pgtype.Numeric `json:"vote_average"`
	VoteCount      int64          `json:"vote_count"`
	IsType         string         `json:"is_type"`
	Active         bool           `json:"active"`
	Slug           string         `json:"slug"`
	Certification  pgtype.Text    `json:"certification"`
}

func (q *Queries) CreateSerie(ctx context.Context, arg CreateSerieParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSerie,
		arg.TmdbID,
		arg.ImdbID,
		arg.OriginalName,
		arg.TitleLat,
		arg.TitleEsp,
		arg.TitleEng,
		arg.Overview,
		arg.FirstAirDate,
		arg.EpisodeRunTime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.IsType,
		arg.Active,
		arg.Slug,
		arg.Certification,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.TmdbID,
		&i.TvdbID,
		&i.ImdbID,
		&i.IsType,
		&i.OriginalName,
		&i.TitleLat,
		&i.TitleEsp,
		&i.TitleEng,
		&i.Overview,
		&i.TrailerKey,
		&i.FirstAirDate,
		&i.EpisodeRunTime,
		&i.PosterPath,
		&i.PosterPathTv,
		&i.BackdropPath,
		&i.LogoPath,
		&i.Certification,
		&i.VoteAverage,
		&i.VoteCount,
		&i.VoteGf,
		&i.Views,
		&i.Premiere,
		&i.Upcoming,
		&i.Premium,
		&i.Active,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCast = `-- name: DeleteCast :exec
DELETE FROM casts WHERE id = $1
`

func (q *Queries) DeleteCast(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCast, id)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGenre, id)
	return err
}

const deleteMediaImage = `-- name: DeleteMediaImage :exec
DELETE FROM media_images WHERE id = $1
`

func (q *Queries) DeleteMediaImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaImage, id)
	return err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const deleteMovieCast = `-- name: DeleteMovieCast :exec
DELETE FROM movie_casts WHERE movie_id = $1 AND cast_id = $2
`

type DeleteMovieCastParams struct {
	MovieID int64 `json:"movie_id"`
	CastID  int64 `json:"cast_id"`
}

func (q *Queries) DeleteMovieCast(ctx context.Context, arg DeleteMovieCastParams) error {
	_, err := q.db.Exec(ctx, deleteMovieCast, arg.MovieID, arg.CastID)
	return err
}

const deleteMovieCollection = `-- name: DeleteMovieCollection :exec
DELETE FROM movie_collections WHERE movie_id = $1 AND collection_id = $2
`

type DeleteMovieCollectionParams struct {
	MovieID      int64 `json:"movie_id"`
	CollectionID int64 `json:"collection_id"`
}

func (q *Queries) DeleteMovieCollection(ctx context.Context, arg DeleteMovieCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteMovieCollection, arg.MovieID, arg.CollectionID)
	return err
}

const deleteMovieGenre = `-- name: DeleteMovieGenre :exec
DELETE FROM movie_genres WHERE movie_id = $1 AND genre_id = $2
`

type DeleteMovieGenreParams struct {
	MovieID int64 `json:"movie_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) DeleteMovieGenre(ctx context.Context, arg DeleteMovieGenreParams) error {
	_, err := q.db.Exec(ctx, deleteMovieGenre, arg.MovieID, arg.GenreID)
	return err
}

const deleteMovieNetwork = `-- name: DeleteMovieNetwork :exec
DELETE FROM movie_networks WHERE movie_id = $1 AND network_id = $2
`

type DeleteMovieNetworkParams struct {
	MovieID   int64 `json:"movie_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) DeleteMovieNetwork(ctx context.Context, arg DeleteMovieNetworkParams) error {
	_, err := q.db.Exec(ctx, deleteMovieNetwork, arg.MovieID, arg.NetworkID)
	return err
}

const deleteNetwork = `-- name: DeleteNetwork :exec
DELETE FROM networks WHERE id = $1
`

func (q *Queries) DeleteNetwork(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNetwork, id)
	return err
}

const deleteSerie = `-- name: DeleteSerie :exec
DELETE FROM series WHERE id = $1
`

func (q *Queries) DeleteSerie(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSerie, id)
	return err
}

const deleteSerieCast = `-- name: DeleteSerieCast :exec
DELETE FROM serie_casts WHERE serie_id = $1 AND cast_id = $2
`

type DeleteSerieCastParams struct {
	SerieID int64 `json:"serie_id"`
	CastID  int64 `json:"cast_id"`
}

func (q *Queries) DeleteSerieCast(ctx context.Context, arg DeleteSerieCastParams) error {
	_, err := q.db.Exec(ctx, deleteSerieCast, arg.SerieID, arg.CastID)
	return err
}

const deleteSerieGenre = `-- name: DeleteSerieGenre :exec
DELETE FROM serie_genres WHERE serie_id = $1 AND genre_id = $2
`

type DeleteSerieGenreParams struct {
	SerieID int64 `json:"serie_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) DeleteSerieGenre(ctx context.Context, arg DeleteSerieGenreParams) error {
	_, err := q.db.Exec(ctx, deleteSerieGenre, arg.SerieID, arg.GenreID)
	return err
}

const deleteSerieNetwork = `-- name: DeleteSerieNetwork :exec
DELETE FROM serie_networks WHERE serie_id = $1 AND network_id = $2
`

type DeleteSerieNetworkParams struct {
	SerieID   int64 `json:"serie_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) DeleteSerieNetwork(ctx context.Context, arg DeleteSerieNetworkParams) error {
	_, err := q.db.Exec(ctx, deleteSerieNetwork, arg.SerieID, arg.NetworkID)
	return err
}

const getCastsPaginated = `-- name: GetCastsPaginated :many
SELECT id, tmdb_id, tvdb_id, uuid, name, original_name, gender, place_of_birth, profile_path, imdb_id, known_for_department, biography, adult, birthday, deathday, views, active, search_vector, created_at, updated_at FROM casts ORDER BY views DESC NULLS LAST LIMIT $1 OFFSET $2
`

type GetCastsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetCastsPaginated(ctx context.Context, arg GetCastsPaginatedParams) ([]Cast, error) {
	rows, err := q.db.Query(ctx, getCastsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cast
	for rows.Next() {
		var i Cast
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.Name,
			&i.OriginalName,
			&i.Gender,
			&i.PlaceOfBirth,
			&i.ProfilePath,
			&i.ImdbID,
			&i.KnownForDepartment,
			&i.Biography,
			&i.Adult,
			&i.Birthday,
			&i.Deathday,
			&i.Views,
			&i.Active,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollections = `-- name: GetCollections :many
SELECT id, tmdb_id, tvdb_id, uuid, original_name, slug, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, search_vector, created_at, updated_at FROM collections ORDER BY id DESC
`

func (q *Queries) GetCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.OriginalName,
			&i.Slug,
			&i.NameLat,
			&i.NameEsp,
			&i.NameEng,
			&i.Overview,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountriesPaginated = `-- name: GetCountriesPaginated :many
SELECT id, uuid, name, english_name, iso_3166_1, logo_path, created_at, updated_at FROM countries ORDER BY name ASC LIMIT $1 OFFSET $2
`

type GetCountriesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetCountriesPaginated(ctx context.Context, arg GetCountriesPaginatedParams) ([]Country, error) {
	rows, err := q.db.Query(ctx, getCountriesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.EnglishName,
			&i.Iso31661,
			&i.LogoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodeMediaSources = `-- name: GetEpisodeMediaSources :many
SELECT id, provider_id, movie_id, episode_id, label, quality, link, link_hash, size_bytes, duration_sec, video_codec, audio_channels, dynamic_range, bit_depth, recap_start, recap_end, opening_start, opening_end, ending_start, ending_end, status, created_at, updated_at, type FROM media_sources WHERE episode_id = $1 ORDER BY id ASC
`

func (q *Queries) GetEpisodeMediaSources(ctx context.Context, episodeID pgtype.Int8) ([]MediaSource, error) {
	rows, err := q.db.Query(ctx, getEpisodeMediaSources, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaSource
	for rows.Next() {
		var i MediaSource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.MovieID,
			&i.EpisodeID,
			&i.Label,
			&i.Quality,
			&i.Link,
			&i.LinkHash,
			&i.SizeBytes,
			&i.DurationSec,
			&i.VideoCodec,
			&i.AudioChannels,
			&i.DynamicRange,
			&i.BitDepth,
			&i.RecapStart,
			&i.RecapEnd,
			&i.OpeningStart,
			&i.OpeningEnd,
			&i.EndingStart,
			&i.EndingEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenres = `-- name: GetGenres :many
SELECT id, tmdb_id, tvdb_id, name_eng, name_esp, slug, image_path, created_at, updated_at FROM genres ORDER BY name_eng ASC
`

func (q *Queries) GetGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.NameEng,
			&i.NameEsp,
			&i.Slug,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaAudioTracks = `-- name: GetMediaAudioTracks :many
SELECT id, media_source_id, track_no, lang, codec, channel_layout, bitrate_kbps, sample_rate_hz, is_default, title, created_at, updated_at FROM media_audio_tracks WHERE media_source_id = $1 ORDER BY track_no ASC
`

func (q *Queries) GetMediaAudioTracks(ctx context.Context, mediaSourceID int64) ([]MediaAudioTrack, error) {
	rows, err := q.db.Query(ctx, getMediaAudioTracks, mediaSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAudioTrack
	for rows.Next() {
		var i MediaAudioTrack
		if err := rows.Scan(
			&i.ID,
			&i.MediaSourceID,
			&i.TrackNo,
			&i.Lang,
			&i.Codec,
			&i.ChannelLayout,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.IsDefault,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaSubtitleTracks = `-- name: GetMediaSubtitleTracks :many
SELECT id, media_source_id, track_no, lang, type, embedded, link, link_hash, zip, forced, cc, is_default, title, status, created_at, updated_at FROM media_subtitle_tracks WHERE media_source_id = $1 ORDER BY track_no ASC
`

func (q *Queries) GetMediaSubtitleTracks(ctx context.Context, mediaSourceID int64) ([]MediaSubtitleTrack, error) {
	rows, err := q.db.Query(ctx, getMediaSubtitleTracks, mediaSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaSubtitleTrack
	for rows.Next() {
		var i MediaSubtitleTrack
		if err := rows.Scan(
			&i.ID,
			&i.MediaSourceID,
			&i.TrackNo,
			&i.Lang,
			&i.Type,
			&i.Embedded,
			&i.Link,
			&i.LinkHash,
			&i.Zip,
			&i.Forced,
			&i.Cc,
			&i.IsDefault,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovie = `-- name: GetMovie :one
SELECT id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, release_date, runtime, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, enable_stream, enable_download, enable_ads_unlock, search_vector, created_at, updated_at FROM movies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.TmdbID,
		&i.TvdbID,
		&i.ImdbID,
		&i.IsType,
		&i.OriginalName,
		&i.TitleLat,
		&i.TitleEsp,
		&i.TitleEng,
		&i.Overview,
		&i.TrailerKey,
		&i.ReleaseDate,
		&i.Runtime,
		&i.PosterPath,
		&i.PosterPathTv,
		&i.BackdropPath,
		&i.LogoPath,
		&i.Certification,
		&i.VoteAverage,
		&i.VoteCount,
		&i.VoteGf,
		&i.Views,
		&i.Premiere,
		&i.Upcoming,
		&i.Premium,
		&i.Active,
		&i.EnableStream,
		&i.EnableDownload,
		&i.EnableAdsUnlock,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieMediaSources = `-- name: GetMovieMediaSources :many
SELECT id, provider_id, movie_id, episode_id, label, quality, link, link_hash, size_bytes, duration_sec, video_codec, audio_channels, dynamic_range, bit_depth, recap_start, recap_end, opening_start, opening_end, ending_start, ending_end, status, created_at, updated_at, type FROM media_sources WHERE movie_id = $1 ORDER BY id ASC
`

func (q *Queries) GetMovieMediaSources(ctx context.Context, movieID pgtype.Int8) ([]MediaSource, error) {
	rows, err := q.db.Query(ctx, getMovieMediaSources, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaSource
	for rows.Next() {
		var i MediaSource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.MovieID,
			&i.EpisodeID,
			&i.Label,
			&i.Quality,
			&i.Link,
			&i.LinkHash,
			&i.SizeBytes,
			&i.DurationSec,
			&i.VideoCodec,
			&i.AudioChannels,
			&i.DynamicRange,
			&i.BitDepth,
			&i.RecapStart,
			&i.RecapEnd,
			&i.OpeningStart,
			&i.OpeningEnd,
			&i.EndingStart,
			&i.EndingEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetworks = `-- name: GetNetworks :many
SELECT id, tmdb_id, tvdb_id, uuid, name, slug, poster_path, backdrop_path, sort_order, created_at, updated_at FROM networks ORDER BY id DESC
`

func (q *Queries) GetNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.Query(ctx, getNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonEpisodes = `-- name: GetSeasonEpisodes :many
SELECT id, episode_number, name, overview, still_path, air_date, enable_stream, enable_download
FROM serie_episodes
WHERE season_id = $1
ORDER BY episode_number ASC
`

type GetSeasonEpisodesRow struct {
	ID             int64       `json:"id"`
	EpisodeNumber  int16       `json:"episode_number"`
	Name           string      `json:"name"`
	Overview       pgtype.Text `json:"overview"`
	StillPath      pgtype.Text `json:"still_path"`
	AirDate        pgtype.Date `json:"air_date"`
	EnableStream   bool        `json:"enable_stream"`
	EnableDownload bool        `json:"enable_download"`
}

func (q *Queries) GetSeasonEpisodes(ctx context.Context, seasonID int64) ([]GetSeasonEpisodesRow, error) {
	rows, err := q.db.Query(ctx, getSeasonEpisodes, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonEpisodesRow
	for rows.Next() {
		var i GetSeasonEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeNumber,
			&i.Name,
			&i.Overview,
			&i.StillPath,
			&i.AirDate,
			&i.EnableStream,
			&i.EnableDownload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSerieSeasons = `-- name: GetSerieSeasons :many
SELECT id, season_number, name, overview, poster_path, air_date
FROM serie_seasons
WHERE serie_id = $1
ORDER BY season_number ASC
`

type GetSerieSeasonsRow struct {
	ID           int64       `json:"id"`
	SeasonNumber int16       `json:"season_number"`
	Name         string      `json:"name"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	AirDate      pgtype.Date `json:"air_date"`
}

func (q *Queries) GetSerieSeasons(ctx context.Context, serieID int64) ([]GetSerieSeasonsRow, error) {
	rows, err := q.db.Query(ctx, getSerieSeasons, serieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSerieSeasonsRow
	for rows.Next() {
		var i GetSerieSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonNumber,
			&i.Name,
			&i.Overview,
			&i.PosterPath,
			&i.AirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingMovies = `-- name: ListTrendingMovies :many
SELECT id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, release_date, runtime, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, enable_stream, enable_download, enable_ads_unlock, search_vector, created_at, updated_at FROM movies
WHERE active = TRUE
ORDER BY views DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListTrendingMoviesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrendingMovies(ctx context.Context, arg ListTrendingMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listTrendingMovies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.TmdbID,
			&i.TvdbID,
			&i.ImdbID,
			&i.IsType,
			&i.OriginalName,
			&i.TitleLat,
			&i.TitleEsp,
			&i.TitleEng,
			&i.Overview,
			&i.TrailerKey,
			&i.ReleaseDate,
			&i.Runtime,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Certification,
			&i.VoteAverage,
			&i.VoteCount,
			&i.VoteGf,
			&i.Views,
			&i.Premiere,
			&i.Upcoming,
			&i.Premium,
			&i.Active,
			&i.EnableStream,
			&i.EnableDownload,
			&i.EnableAdsUnlock,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCasts = `-- name: SearchCasts :many
SELECT id, tmdb_id, tvdb_id, uuid, name, original_name, gender, place_of_birth, profile_path, imdb_id, known_for_department, biography, adult, birthday, deathday, views, active, search_vector, created_at, updated_at FROM casts WHERE name ILIKE '%' || $1 || '%' LIMIT 10
`

func (q *Queries) SearchCasts(ctx context.Context, dollar_1 pgtype.Text) ([]Cast, error) {
	rows, err := q.db.Query(ctx, searchCasts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cast
	for rows.Next() {
		var i Cast
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.Name,
			&i.OriginalName,
			&i.Gender,
			&i.PlaceOfBirth,
			&i.ProfilePath,
			&i.ImdbID,
			&i.KnownForDepartment,
			&i.Biography,
			&i.Adult,
			&i.Birthday,
			&i.Deathday,
			&i.Views,
			&i.Active,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCollections = `-- name: SearchCollections :many
SELECT id, tmdb_id, tvdb_id, uuid, original_name, slug, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, search_vector, created_at, updated_at FROM collections WHERE original_name ILIKE '%' || $1 || '%' OR name_lat ILIKE '%' || $1 || '%' LIMIT 10
`

func (q *Queries) SearchCollections(ctx context.Context, dollar_1 pgtype.Text) ([]Collection, error) {
	rows, err := q.db.Query(ctx, searchCollections, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.OriginalName,
			&i.Slug,
			&i.NameLat,
			&i.NameEsp,
			&i.NameEng,
			&i.Overview,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCountries = `-- name: SearchCountries :many
SELECT id, uuid, name, english_name, iso_3166_1, logo_path, created_at, updated_at FROM countries 
WHERE name ILIKE '%' || $1 || '%' OR english_name ILIKE '%' || $1 || '%' OR iso_3166_1 ILIKE '%' || $1 || '%' 
ORDER BY name ASC LIMIT 10
`

func (q *Queries) SearchCountries(ctx context.Context, dollar_1 pgtype.Text) ([]Country, error) {
	rows, err := q.db.Query(ctx, searchCountries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.EnglishName,
			&i.Iso31661,
			&i.LogoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGenres = `-- name: SearchGenres :many
SELECT id, tmdb_id, tvdb_id, name_eng, name_esp, slug, image_path, created_at, updated_at FROM genres WHERE name_eng ILIKE '%' || $1 || '%' OR name_esp ILIKE '%' || $1 || '%' LIMIT 10
`

func (q *Queries) SearchGenres(ctx context.Context, dollar_1 pgtype.Text) ([]Genre, error) {
	rows, err := q.db.Query(ctx, searchGenres, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.NameEng,
			&i.NameEsp,
			&i.Slug,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, release_date, runtime, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, enable_stream, enable_download, enable_ads_unlock, search_vector, created_at, updated_at FROM movies
WHERE active = TRUE
  AND search_vector @@ plainto_tsquery('spanish', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('spanish', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchMoviesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, searchMovies, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.TmdbID,
			&i.TvdbID,
			&i.ImdbID,
			&i.IsType,
			&i.OriginalName,
			&i.TitleLat,
			&i.TitleEsp,
			&i.TitleEng,
			&i.Overview,
			&i.TrailerKey,
			&i.ReleaseDate,
			&i.Runtime,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Certification,
			&i.VoteAverage,
			&i.VoteCount,
			&i.VoteGf,
			&i.Views,
			&i.Premiere,
			&i.Upcoming,
			&i.Premium,
			&i.Active,
			&i.EnableStream,
			&i.EnableDownload,
			&i.EnableAdsUnlock,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNetworks = `-- name: SearchNetworks :many
SELECT id, tmdb_id, tvdb_id, uuid, name, slug, poster_path, backdrop_path, sort_order, created_at, updated_at FROM networks WHERE name ILIKE '%' || $1 || '%' LIMIT 10
`

func (q *Queries) SearchNetworks(ctx context.Context, dollar_1 pgtype.Text) ([]Network, error) {
	rows, err := q.db.Query(ctx, searchNetworks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Uuid,
			&i.Name,
			&i.Slug,
			&i.PosterPath,
			&i.BackdropPath,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, uuid, slug, tmdb_id, tvdb_id, imdb_id, is_type, original_name, title_lat, title_esp, title_eng, overview, trailer_key, first_air_date, episode_run_time, poster_path, poster_path_tv, backdrop_path, logo_path, certification, vote_average, vote_count, vote_gf, views, premiere, upcoming, premium, active, search_vector, created_at, updated_at FROM series
WHERE active = TRUE
  AND search_vector @@ plainto_tsquery('spanish', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('spanish', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchSeriesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, searchSeries, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.TmdbID,
			&i.TvdbID,
			&i.ImdbID,
			&i.IsType,
			&i.OriginalName,
			&i.TitleLat,
			&i.TitleEsp,
			&i.TitleEng,
			&i.Overview,
			&i.TrailerKey,
			&i.FirstAirDate,
			&i.EpisodeRunTime,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Certification,
			&i.VoteAverage,
			&i.VoteCount,
			&i.VoteGf,
			&i.Views,
			&i.Premiere,
			&i.Upcoming,
			&i.Premium,
			&i.Active,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCast = `-- name: UpdateCast :one
UPDATE casts SET name = $2, original_name = $3, gender = $4, place_of_birth = $5, profile_path = $6, imdb_id = $7, known_for_department = $8, biography = $9, adult = $10, birthday = $11, deathday = $12 WHERE id = $1 RETURNING id, tmdb_id, tvdb_id, uuid, name, original_name, gender, place_of_birth, profile_path, imdb_id, known_for_department, biography, adult, birthday, deathday, views, active, search_vector, created_at, updated_at
`

type UpdateCastParams struct {
	ID                 int64       `json:"id"`
	Name               string      `json:"name"`
	OriginalName       pgtype.Text `json:"original_name"`
	Gender             pgtype.Int2 `json:"gender"`
	PlaceOfBirth       pgtype.Text `json:"place_of_birth"`
	ProfilePath        pgtype.Text `json:"profile_path"`
	ImdbID             pgtype.Text `json:"imdb_id"`
	KnownForDepartment pgtype.Text `json:"known_for_department"`
	Biography          pgtype.Text `json:"biography"`
	Adult              bool        `json:"adult"`
	Birthday           pgtype.Date `json:"birthday"`
	Deathday           pgtype.Date `json:"deathday"`
}

func (q *Queries) UpdateCast(ctx context.Context, arg UpdateCastParams) (Cast, error) {
	row := q.db.QueryRow(ctx, updateCast,
		arg.ID,
		arg.Name,
		arg.OriginalName,
		arg.Gender,
		arg.PlaceOfBirth,
		arg.ProfilePath,
		arg.ImdbID,
		arg.KnownForDepartment,
		arg.Biography,
		arg.Adult,
		arg.Birthday,
		arg.Deathday,
	)
	var i Cast
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.Name,
		&i.OriginalName,
		&i.Gender,
		&i.PlaceOfBirth,
		&i.ProfilePath,
		&i.ImdbID,
		&i.KnownForDepartment,
		&i.Biography,
		&i.Adult,
		&i.Birthday,
		&i.Deathday,
		&i.Views,
		&i.Active,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections SET original_name = $2, name_lat = $3, name_esp = $4, name_eng = $5, overview = $6, poster_path = $7, backdrop_path = $8, slug = $9 WHERE id = $1 RETURNING id, tmdb_id, tvdb_id, uuid, original_name, slug, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, search_vector, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID           int64       `json:"id"`
	OriginalName string      `json:"original_name"`
	NameLat      pgtype.Text `json:"name_lat"`
	NameEsp      pgtype.Text `json:"name_esp"`
	NameEng      pgtype.Text `json:"name_eng"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.OriginalName,
		arg.NameLat,
		arg.NameEsp,
		arg.NameEng,
		arg.Overview,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Slug,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.OriginalName,
		&i.Slug,
		&i.NameLat,
		&i.NameEsp,
		&i.NameEng,
		&i.Overview,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries SET name = $2, english_name = $3, iso_3166_1 = $4, logo_path = $5 WHERE id = $1 RETURNING id, uuid, name, english_name, iso_3166_1, logo_path, created_at, updated_at
`

type UpdateCountryParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	EnglishName pgtype.Text `json:"english_name"`
	Iso31661    string      `json:"iso_3166_1"`
	LogoPath    pgtype.Text `json:"logo_path"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.Name,
		arg.EnglishName,
		arg.Iso31661,
		arg.LogoPath,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.EnglishName,
		&i.Iso31661,
		&i.LogoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGenre = `-- name: UpdateGenre :one
UPDATE genres SET name_eng = $2, name_esp = $3, image_path = $4, slug = $5 WHERE id = $1 RETURNING id, tmdb_id, tvdb_id, name_eng, name_esp, slug, image_path, created_at, updated_at
`

type UpdateGenreParams struct {
	ID        int64       `json:"id"`
	NameEng   string      `json:"name_eng"`
	NameEsp   pgtype.Text `json:"name_esp"`
	ImagePath pgtype.Text `json:"image_path"`
	Slug      string      `json:"slug"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, updateGenre,
		arg.ID,
		arg.NameEng,
		arg.NameEsp,
		arg.ImagePath,
		arg.Slug,
	)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.NameEng,
		&i.NameEsp,
		&i.Slug,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMovieBasic = `-- name: UpdateMovieBasic :exec
UPDATE movies 
SET 
  original_name = $2,
  slug = $3,
  title_lat = $4, 
  title_esp = $5,
  title_eng = $6,
  overview = $7, 
  trailer_key = $8,
  release_date = $9,
  runtime = $10,
  vote_average = $11,
  vote_count = $12,
  active = $13,
  premium = $14,
  premiere = $15,
  upcoming = $16,
  enable_stream = $17,
  enable_download = $18,
  certification = COALESCE($19, certification),
  updated_at = NOW()
WHERE id = $1
`

type UpdateMovieBasicParams struct {
	ID             int64          `json:"id"`
	OriginalName   string         `json:"original_name"`
	Slug           string         `json:"slug"`
	TitleLat       pgtype.Text    `json:"title_lat"`
	TitleEsp       pgtype.Text    `json:"title_esp"`
	TitleEng       pgtype.Text    `json:"title_eng"`
	Overview       pgtype.Text    `json:"overview"`
	TrailerKey     pgtype.Text    `json:"trailer_key"`
	ReleaseDate    pgtype.Date    `json:"release_date"`
	Runtime        pgtype.Int2    `json:"runtime"`
	VoteAverage    pgtype.Numeric `json:"vote_average"`
	VoteCount      int64          `json:"vote_count"`
	Active         bool           `json:"active"`
	Premium        bool           `json:"premium"`
	Premiere       bool           `json:"premiere"`
	Upcoming       bool           `json:"upcoming"`
	EnableStream   bool           `json:"enable_stream"`
	EnableDownload bool           `json:"enable_download"`
	Certification  pgtype.Text    `json:"certification"`
}

func (q *Queries) UpdateMovieBasic(ctx context.Context, arg UpdateMovieBasicParams) error {
	_, err := q.db.Exec(ctx, updateMovieBasic,
		arg.ID,
		arg.OriginalName,
		arg.Slug,
		arg.TitleLat,
		arg.TitleEsp,
		arg.TitleEng,
		arg.Overview,
		arg.TrailerKey,
		arg.ReleaseDate,
		arg.Runtime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Active,
		arg.Premium,
		arg.Premiere,
		arg.Upcoming,
		arg.EnableStream,
		arg.EnableDownload,
		arg.Certification,
	)
	return err
}

const updateNetwork = `-- name: UpdateNetwork :one
UPDATE networks SET name = $2, poster_path = $3, backdrop_path = $4, slug = $5 WHERE id = $1 RETURNING id, tmdb_id, tvdb_id, uuid, name, slug, poster_path, backdrop_path, sort_order, created_at, updated_at
`

type UpdateNetworkParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, updateNetwork,
		arg.ID,
		arg.Name,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Slug,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Uuid,
		&i.Name,
		&i.Slug,
		&i.PosterPath,
		&i.BackdropPath,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSerieBasic = `-- name: UpdateSerieBasic :exec
UPDATE series 
SET 
  original_name = $2,
  slug = $3,
  title_lat = $4, 
  title_esp = $5,
  title_eng = $6,
  overview = $7, 
  trailer_key = $8,
  first_air_date = $9,
  episode_run_time = $10,
  vote_average = $11,
  vote_count = $12,
  active = $13,
  premium = $14,
  premiere = $15,
  upcoming = $16,
  certification = COALESCE($17, certification),
  updated_at = NOW()
WHERE id = $1
`

type UpdateSerieBasicParams struct {
	ID             int64          `json:"id"`
	OriginalName   string         `json:"original_name"`
	Slug           string         `json:"slug"`
	TitleLat       pgtype.Text    `json:"title_lat"`
	TitleEsp       pgtype.Text    `json:"title_esp"`
	TitleEng       pgtype.Text    `json:"title_eng"`
	Overview       pgtype.Text    `json:"overview"`
	TrailerKey     pgtype.Text    `json:"trailer_key"`
	FirstAirDate   pgtype.Date    `json:"first_air_date"`
	EpisodeRunTime pgtype.Int2    `json:"episode_run_time"`
	VoteAverage    pgtype.Numeric `json:"vote_average"`
	VoteCount      int64          `json:"vote_count"`
	Active         bool           `json:"active"`
	Premium        bool           `json:"premium"`
	Premiere       bool           `json:"premiere"`
	Upcoming       bool           `json:"upcoming"`
	Certification  pgtype.Text    `json:"certification"`
}

func (q *Queries) UpdateSerieBasic(ctx context.Context, arg UpdateSerieBasicParams) error {
	_, err := q.db.Exec(ctx, updateSerieBasic,
		arg.ID,
		arg.OriginalName,
		arg.Slug,
		arg.TitleLat,
		arg.TitleEsp,
		arg.TitleEng,
		arg.Overview,
		arg.TrailerKey,
		arg.FirstAirDate,
		arg.EpisodeRunTime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Active,
		arg.Premium,
		arg.Premiere,
		arg.Upcoming,
		arg.Certification,
	)
	return err
}
