// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_filters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogFilterMovies = `-- name: CatalogFilterMovies :many
SELECT 
    m.id, 
    m.slug, 
    COALESCE(m.title_lat, m.original_name) AS title, 
    m.overview, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = m.id AND type = 'poster' AND is_main = true LIMIT 1), m.poster_path) AS poster_path,
    m.release_date,
    m.vote_average,
    COALESCE(m.views, 0)::bigint AS views
FROM movies m
WHERE m.active = true
  AND ($3::varchar IS NULL OR m.is_type = $3)
  AND ($4::int IS NULL OR EXTRACT(YEAR FROM m.release_date) = $4)
  AND ($5::varchar IS NULL OR m.search_vector @@ plainto_tsquery('spanish', $5))
  AND ($6::bigint IS NULL OR EXISTS (SELECT 1 FROM movie_genres mg WHERE mg.movie_id = m.id AND mg.genre_id = $6))
  AND ($7::bigint IS NULL OR EXISTS (SELECT 1 FROM movie_networks mn WHERE mn.movie_id = m.id AND mn.network_id = $7))
  AND ($8::bigint IS NULL OR EXISTS (SELECT 1 FROM movie_countries mc WHERE mc.movie_id = m.id AND mc.country_id = $8))
ORDER BY 
  CASE WHEN $9::varchar = 'recent' THEN m.release_date END DESC,
  CASE WHEN $9::varchar = 'popular' THEN m.views END DESC,
  CASE WHEN $9::varchar = 'rating' THEN m.vote_average END DESC,
  m.id DESC
LIMIT $1 OFFSET $2
`

type CatalogFilterMoviesParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	IsType      pgtype.Text `json:"is_type"`
	Year        pgtype.Int4 `json:"year"`
	SearchQuery pgtype.Text `json:"search_query"`
	GenreID     pgtype.Int8 `json:"genre_id"`
	NetworkID   pgtype.Int8 `json:"network_id"`
	CountryID   pgtype.Int8 `json:"country_id"`
	SortBy      pgtype.Text `json:"sort_by"`
}

type CatalogFilterMoviesRow struct {
	ID          int64          `json:"id"`
	Slug        string         `json:"slug"`
	Title       string         `json:"title"`
	Overview    pgtype.Text    `json:"overview"`
	PosterPath  pgtype.Text    `json:"poster_path"`
	ReleaseDate pgtype.Date    `json:"release_date"`
	VoteAverage pgtype.Numeric `json:"vote_average"`
	Views       int64          `json:"views"`
}

func (q *Queries) CatalogFilterMovies(ctx context.Context, arg CatalogFilterMoviesParams) ([]CatalogFilterMoviesRow, error) {
	rows, err := q.db.Query(ctx, catalogFilterMovies,
		arg.Limit,
		arg.Offset,
		arg.IsType,
		arg.Year,
		arg.SearchQuery,
		arg.GenreID,
		arg.NetworkID,
		arg.CountryID,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogFilterMoviesRow
	for rows.Next() {
		var i CatalogFilterMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.ReleaseDate,
			&i.VoteAverage,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogFilterSeries = `-- name: CatalogFilterSeries :many
SELECT 
    s.id, 
    s.slug, 
    COALESCE(s.title_lat, s.original_name) AS title, 
    s.overview, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = s.id AND type = 'poster' AND is_main = true LIMIT 1), s.poster_path) AS poster_path,
    s.first_air_date,
    s.vote_average,
    COALESCE(s.views, 0)::bigint AS views
FROM series s
WHERE s.active = true
  AND ($3::varchar IS NULL OR s.is_type = $3)
  AND ($4::int IS NULL OR EXTRACT(YEAR FROM s.first_air_date) = $4)
  AND ($5::varchar IS NULL OR s.search_vector @@ plainto_tsquery('spanish', $5))
  AND ($6::bigint IS NULL OR EXISTS (SELECT 1 FROM serie_genres sg WHERE sg.serie_id = s.id AND sg.genre_id = $6))
  AND ($7::bigint IS NULL OR EXISTS (SELECT 1 FROM serie_networks sn WHERE sn.serie_id = s.id AND sn.network_id = $7))
  AND ($8::bigint IS NULL OR EXISTS (SELECT 1 FROM serie_countries sc WHERE sc.serie_id = s.id AND sc.country_id = $8))
ORDER BY 
  CASE WHEN $9::varchar = 'recent' THEN s.first_air_date END DESC,
  CASE WHEN $9::varchar = 'popular' THEN s.views END DESC,
  CASE WHEN $9::varchar = 'rating' THEN s.vote_average END DESC,
  s.id DESC
LIMIT $1 OFFSET $2
`

type CatalogFilterSeriesParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	IsType      pgtype.Text `json:"is_type"`
	Year        pgtype.Int4 `json:"year"`
	SearchQuery pgtype.Text `json:"search_query"`
	GenreID     pgtype.Int8 `json:"genre_id"`
	NetworkID   pgtype.Int8 `json:"network_id"`
	CountryID   pgtype.Int8 `json:"country_id"`
	SortBy      pgtype.Text `json:"sort_by"`
}

type CatalogFilterSeriesRow struct {
	ID           int64          `json:"id"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Overview     pgtype.Text    `json:"overview"`
	PosterPath   pgtype.Text    `json:"poster_path"`
	FirstAirDate pgtype.Date    `json:"first_air_date"`
	VoteAverage  pgtype.Numeric `json:"vote_average"`
	Views        int64          `json:"views"`
}

func (q *Queries) CatalogFilterSeries(ctx context.Context, arg CatalogFilterSeriesParams) ([]CatalogFilterSeriesRow, error) {
	rows, err := q.db.Query(ctx, catalogFilterSeries,
		arg.Limit,
		arg.Offset,
		arg.IsType,
		arg.Year,
		arg.SearchQuery,
		arg.GenreID,
		arg.NetworkID,
		arg.CountryID,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogFilterSeriesRow
	for rows.Next() {
		var i CatalogFilterSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.FirstAirDate,
			&i.VoteAverage,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
