// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaReport = `-- name: CreateMediaReport :one
INSERT INTO media_reports (
    user_id, media_type, media_id, reason, details
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, media_type, media_id, reason, details, status, created_at, updated_at
`

type CreateMediaReportParams struct {
	UserID    int64       `json:"user_id"`
	MediaType string      `json:"media_type"`
	MediaID   int64       `json:"media_id"`
	Reason    string      `json:"reason"`
	Details   pgtype.Text `json:"details"`
}

func (q *Queries) CreateMediaReport(ctx context.Context, arg CreateMediaReportParams) (MediaReport, error) {
	row := q.db.QueryRow(ctx, createMediaReport,
		arg.UserID,
		arg.MediaType,
		arg.MediaID,
		arg.Reason,
		arg.Details,
	)
	var i MediaReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaType,
		&i.MediaID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaRequest = `-- name: CreateMediaRequest :one
INSERT INTO media_requests (
    user_id, tmdb_id, title, media_type, notes
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, tmdb_id, title, media_type, status, notes, created_at, updated_at
`

type CreateMediaRequestParams struct {
	UserID    int64       `json:"user_id"`
	TmdbID    pgtype.Int4 `json:"tmdb_id"`
	Title     string      `json:"title"`
	MediaType string      `json:"media_type"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreateMediaRequest(ctx context.Context, arg CreateMediaRequestParams) (MediaRequest, error) {
	row := q.db.QueryRow(ctx, createMediaRequest,
		arg.UserID,
		arg.TmdbID,
		arg.Title,
		arg.MediaType,
		arg.Notes,
	)
	var i MediaRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.MediaType,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMediaReports = `-- name: ListUserMediaReports :many
SELECT id, user_id, media_type, media_id, reason, details, status, created_at, updated_at FROM media_reports
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserMediaReportsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserMediaReports(ctx context.Context, arg ListUserMediaReportsParams) ([]MediaReport, error) {
	rows, err := q.db.Query(ctx, listUserMediaReports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaReport
	for rows.Next() {
		var i MediaReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaType,
			&i.MediaID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMediaRequests = `-- name: ListUserMediaRequests :many
SELECT id, user_id, tmdb_id, title, media_type, status, notes, created_at, updated_at FROM media_requests
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserMediaRequestsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserMediaRequests(ctx context.Context, arg ListUserMediaRequestsParams) ([]MediaRequest, error) {
	rows, err := q.db.Query(ctx, listUserMediaRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaRequest
	for rows.Next() {
		var i MediaRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TmdbID,
			&i.Title,
			&i.MediaType,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
