// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaReport = `-- name: CreateMediaReport :one
INSERT INTO reports (
    user_id, content_type, content_id, reason, details
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, content_type, content_id, reason, details, status, created_at, updated_at
`

type CreateMediaReportParams struct {
	UserID      int64       `json:"user_id"`
	ContentType string      `json:"content_type"`
	ContentID   int64       `json:"content_id"`
	Reason      string      `json:"reason"`
	Details     pgtype.Text `json:"details"`
}

func (q *Queries) CreateMediaReport(ctx context.Context, arg CreateMediaReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createMediaReport,
		arg.UserID,
		arg.ContentType,
		arg.ContentID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentType,
		&i.ContentID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaRequest = `-- name: CreateMediaRequest :one
INSERT INTO content_requests (
    user_id, tmdb_id, title, notes
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, title, tmdb_id, status, notes, created_at, updated_at
`

type CreateMediaRequestParams struct {
	UserID int64       `json:"user_id"`
	TmdbID pgtype.Int8 `json:"tmdb_id"`
	Title  string      `json:"title"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) CreateMediaRequest(ctx context.Context, arg CreateMediaRequestParams) (ContentRequest, error) {
	row := q.db.QueryRow(ctx, createMediaRequest,
		arg.UserID,
		arg.TmdbID,
		arg.Title,
		arg.Notes,
	)
	var i ContentRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.TmdbID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMediaReports = `-- name: ListUserMediaReports :many
SELECT id, user_id, content_type, content_id, reason, details, status, created_at, updated_at FROM reports
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserMediaReportsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserMediaReports(ctx context.Context, arg ListUserMediaReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listUserMediaReports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentType,
			&i.ContentID,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMediaRequests = `-- name: ListUserMediaRequests :many
SELECT id, user_id, title, tmdb_id, status, notes, created_at, updated_at FROM content_requests
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserMediaRequestsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserMediaRequests(ctx context.Context, arg ListUserMediaRequestsParams) ([]ContentRequest, error) {
	rows, err := q.db.Query(ctx, listUserMediaRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentRequest
	for rows.Next() {
		var i ContentRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.TmdbID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
