// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTokenWithDevice = `-- name: CheckTokenWithDevice :one
SELECT 
    t.id AS token_id,
    t.tokenable_type,
    t.tokenable_id,
    t.expires_at,
    d.id AS device_id,
    d.active AS device_active,
    u.id AS user_id,
    u.is_shadowbanned
FROM personal_access_tokens t
JOIN devices d ON t.device_id = d.id
JOIN users u ON t.tokenable_id = u.id
WHERE t.token = $1 AND t.tokenable_type = 'user'
LIMIT 1
`

type CheckTokenWithDeviceRow struct {
	TokenID        int64              `json:"token_id"`
	TokenableType  string             `json:"tokenable_type"`
	TokenableID    int64              `json:"tokenable_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	DeviceID       int64              `json:"device_id"`
	DeviceActive   bool               `json:"device_active"`
	UserID         int64              `json:"user_id"`
	IsShadowbanned bool               `json:"is_shadowbanned"`
}

func (q *Queries) CheckTokenWithDevice(ctx context.Context, token string) (CheckTokenWithDeviceRow, error) {
	row := q.db.QueryRow(ctx, checkTokenWithDevice, token)
	var i CheckTokenWithDeviceRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenableType,
		&i.TokenableID,
		&i.ExpiresAt,
		&i.DeviceID,
		&i.DeviceActive,
		&i.UserID,
		&i.IsShadowbanned,
	)
	return i, err
}

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_tokens (
    tokenable_type, tokenable_id, name, client, device_id, token, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tokenable_type, tokenable_id, name, client, device_id, token, abilities, last_used_at, expires_at, created_at, updated_at
`

type CreatePersonalAccessTokenParams struct {
	TokenableType string             `json:"tokenable_type"`
	TokenableID   int64              `json:"tokenable_id"`
	Name          string             `json:"name"`
	Client        pgtype.Text        `json:"client"`
	DeviceID      pgtype.Int8        `json:"device_id"`
	Token         string             `json:"token"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken,
		arg.TokenableType,
		arg.TokenableID,
		arg.Name,
		arg.Client,
		arg.DeviceID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenableType,
		&i.TokenableID,
		&i.Name,
		&i.Client,
		&i.DeviceID,
		&i.Token,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
  user_id, name, pin_enabled, pin_hash
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, name, active, pin_enabled, pin_hash, pin_failed_attempts, pin_locked_until, created_at, updated_at, deleted_at
`

type CreateProfileParams struct {
	UserID     int64       `json:"user_id"`
	Name       string      `json:"name"`
	PinEnabled bool        `json:"pin_enabled"`
	PinHash    pgtype.Text `json:"pin_hash"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Name,
		arg.PinEnabled,
		arg.PinHash,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Active,
		&i.PinEnabled,
		&i.PinHash,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING id, name, email, email_verified_at, password_hash, remember_token, last_vip_win_at, last_login_at, reactivated_at, reactivation_count, xp, current_streak, longest_streak, is_shadowbanned, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.RememberToken,
		&i.LastVipWinAt,
		&i.LastLoginAt,
		&i.ReactivatedAt,
		&i.ReactivationCount,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.IsShadowbanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFirstActiveProfile = `-- name: GetFirstActiveProfile :one
SELECT id, name, active FROM profiles WHERE user_id = $1 AND active = true AND deleted_at IS NULL ORDER BY id ASC LIMIT 1
`

type GetFirstActiveProfileRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) GetFirstActiveProfile(ctx context.Context, userID int64) (GetFirstActiveProfileRow, error) {
	row := q.db.QueryRow(ctx, getFirstActiveProfile, userID)
	var i GetFirstActiveProfileRow
	err := row.Scan(&i.ID, &i.Name, &i.Active)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, email_verified_at, password_hash, remember_token, last_vip_win_at, last_login_at, reactivated_at, reactivation_count, xp, current_streak, longest_streak, is_shadowbanned, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.RememberToken,
		&i.LastVipWinAt,
		&i.LastLoginAt,
		&i.ReactivatedAt,
		&i.ReactivationCount,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.IsShadowbanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified_at, password_hash, remember_token, last_vip_win_at, last_login_at, reactivated_at, reactivation_count, xp, current_streak, longest_streak, is_shadowbanned, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.RememberToken,
		&i.LastVipWinAt,
		&i.LastLoginAt,
		&i.ReactivatedAt,
		&i.ReactivationCount,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.IsShadowbanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserProfiles = `-- name: ListUserProfiles :many
SELECT id, user_id, name, active, pin_enabled, pin_hash, pin_failed_attempts, pin_locked_until, created_at, updated_at, deleted_at FROM profiles
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListUserProfiles(ctx context.Context, userID int64) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listUserProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Active,
			&i.PinEnabled,
			&i.PinHash,
			&i.PinFailedAttempts,
			&i.PinLockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO devices (
  user_id, platform, fingerprint, device_brand, device_model, os_version, last_ip, session_id, last_user_agent
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (user_id, fingerprint) 
DO UPDATE SET 
    session_id = EXCLUDED.session_id,
    device_brand = EXCLUDED.device_brand,
    device_model = EXCLUDED.device_model,
    os_version = EXCLUDED.os_version,
    last_ip = EXCLUDED.last_ip,
    last_user_agent = EXCLUDED.last_user_agent,
    last_login_at = NOW(),
    active = TRUE
RETURNING id, user_id, active_profile_id, session_id, name, platform, fingerprint, app_version, device_brand, device_model, os_version, last_ip, last_user_agent, first_login_at, last_login_at, active, created_at, updated_at
`

type RegisterDeviceParams struct {
	UserID        int64       `json:"user_id"`
	Platform      string      `json:"platform"`
	Fingerprint   string      `json:"fingerprint"`
	DeviceBrand   pgtype.Text `json:"device_brand"`
	DeviceModel   pgtype.Text `json:"device_model"`
	OsVersion     pgtype.Text `json:"os_version"`
	LastIp        *netip.Addr `json:"last_ip"`
	SessionID     pgtype.Text `json:"session_id"`
	LastUserAgent pgtype.Text `json:"last_user_agent"`
}

func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice,
		arg.UserID,
		arg.Platform,
		arg.Fingerprint,
		arg.DeviceBrand,
		arg.DeviceModel,
		arg.OsVersion,
		arg.LastIp,
		arg.SessionID,
		arg.LastUserAgent,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveProfileID,
		&i.SessionID,
		&i.Name,
		&i.Platform,
		&i.Fingerprint,
		&i.AppVersion,
		&i.DeviceBrand,
		&i.DeviceModel,
		&i.OsVersion,
		&i.LastIp,
		&i.LastUserAgent,
		&i.FirstLoginAt,
		&i.LastLoginAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
DELETE FROM personal_access_tokens WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeToken, token)
	return err
}

const updateDeviceIP = `-- name: UpdateDeviceIP :exec
UPDATE devices 
SET last_ip = $2, last_login_at = NOW() 
WHERE id = $1
`

type UpdateDeviceIPParams struct {
	ID     int64       `json:"id"`
	LastIp *netip.Addr `json:"last_ip"`
}

func (q *Queries) UpdateDeviceIP(ctx context.Context, arg UpdateDeviceIPParams) error {
	_, err := q.db.Exec(ctx, updateDeviceIP, arg.ID, arg.LastIp)
	return err
}

const updateUserLogin = `-- name: UpdateUserLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLogin, id)
	return err
}
