// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSyncRun = `-- name: CompleteSyncRun :exec
UPDATE drive.sync_runs
SET status = $2, finished_at = NOW(),
    files_found = $3, items_created = $4, items_updated = $5,
    error_message = $6
WHERE id = $1
`

type CompleteSyncRunParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	FilesFound   pgtype.Int4 `json:"files_found"`
	ItemsCreated pgtype.Int4 `json:"items_created"`
	ItemsUpdated pgtype.Int4 `json:"items_updated"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CompleteSyncRun(ctx context.Context, arg CompleteSyncRunParams) error {
	_, err := q.db.Exec(ctx, completeSyncRun,
		arg.ID,
		arg.Status,
		arg.FilesFound,
		arg.ItemsCreated,
		arg.ItemsUpdated,
		arg.ErrorMessage,
	)
	return err
}

const createDriveSource = `-- name: CreateDriveSource :one
INSERT INTO drive.sources (
    service_account_id, name, folder_id, provider, sync_interval_minutes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, service_account_id, name, folder_id, provider, sync_interval_minutes, created_at, updated_at
`

type CreateDriveSourceParams struct {
	ServiceAccountID    pgtype.Int8 `json:"service_account_id"`
	Name                string      `json:"name"`
	FolderID            string      `json:"folder_id"`
	Provider            string      `json:"provider"`
	SyncIntervalMinutes pgtype.Int4 `json:"sync_interval_minutes"`
}

func (q *Queries) CreateDriveSource(ctx context.Context, arg CreateDriveSourceParams) (DriveSource, error) {
	row := q.db.QueryRow(ctx, createDriveSource,
		arg.ServiceAccountID,
		arg.Name,
		arg.FolderID,
		arg.Provider,
		arg.SyncIntervalMinutes,
	)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.Name,
		&i.FolderID,
		&i.Provider,
		&i.SyncIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO drive.service_accounts (
    name, email, provider, credentials_json, quota_limit_bytes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, email, provider, credentials_json, quota_limit_bytes, quota_used_bytes, is_active, status, created_at, updated_at
`

type CreateServiceAccountParams struct {
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	Provider        string      `json:"provider"`
	CredentialsJson string      `json:"credentials_json"`
	QuotaLimitBytes pgtype.Int8 `json:"quota_limit_bytes"`
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (DriveServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount,
		arg.Name,
		arg.Email,
		arg.Provider,
		arg.CredentialsJson,
		arg.QuotaLimitBytes,
	)
	var i DriveServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.CredentialsJson,
		&i.QuotaLimitBytes,
		&i.QuotaUsedBytes,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveServiceAccounts = `-- name: GetActiveServiceAccounts :many
SELECT id, name, email, provider, credentials_json, quota_limit_bytes, quota_used_bytes, is_active, status, created_at, updated_at FROM drive.service_accounts
WHERE is_active = TRUE AND status = 'healthy'
ORDER BY quota_used_bytes ASC
`

func (q *Queries) GetActiveServiceAccounts(ctx context.Context) ([]DriveServiceAccount, error) {
	rows, err := q.db.Query(ctx, getActiveServiceAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveServiceAccount
	for rows.Next() {
		var i DriveServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Provider,
			&i.CredentialsJson,
			&i.QuotaLimitBytes,
			&i.QuotaUsedBytes,
			&i.IsActive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO drive.sync_runs (
    source_id, sync_session, status, started_at
) VALUES (
    $1, $2, 'running', NOW()
)
RETURNING id, source_id, sync_session, status, files_found, items_created, items_updated, error_message, started_at, finished_at
`

type StartSyncRunParams struct {
	SourceID    pgtype.Int8 `json:"source_id"`
	SyncSession string      `json:"sync_session"`
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (DriveSyncRun, error) {
	row := q.db.QueryRow(ctx, startSyncRun, arg.SourceID, arg.SyncSession)
	var i DriveSyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SyncSession,
		&i.Status,
		&i.FilesFound,
		&i.ItemsCreated,
		&i.ItemsUpdated,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const syncDriveItem = `-- name: SyncDriveItem :one
INSERT INTO drive.items (
    source_id, remote_id, name, mime_type, size_bytes, 
    md5_checksum, video_codec, width, height, duration_sec
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (source_id, remote_id) DO UPDATE SET
    name = EXCLUDED.name,
    size_bytes = EXCLUDED.size_bytes,
    status = 'available',
    updated_at = NOW()
RETURNING id, source_id, remote_id, name, mime_type, size_bytes, md5_checksum, video_codec, width, height, duration_sec, status, created_at, updated_at
`

type SyncDriveItemParams struct {
	SourceID    pgtype.Int8 `json:"source_id"`
	RemoteID    string      `json:"remote_id"`
	Name        string      `json:"name"`
	MimeType    pgtype.Text `json:"mime_type"`
	SizeBytes   pgtype.Int8 `json:"size_bytes"`
	Md5Checksum pgtype.Text `json:"md5_checksum"`
	VideoCodec  pgtype.Text `json:"video_codec"`
	Width       pgtype.Int4 `json:"width"`
	Height      pgtype.Int4 `json:"height"`
	DurationSec pgtype.Int4 `json:"duration_sec"`
}

func (q *Queries) SyncDriveItem(ctx context.Context, arg SyncDriveItemParams) (DriveItem, error) {
	row := q.db.QueryRow(ctx, syncDriveItem,
		arg.SourceID,
		arg.RemoteID,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.Md5Checksum,
		arg.VideoCodec,
		arg.Width,
		arg.Height,
		arg.DurationSec,
	)
	var i DriveItem
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RemoteID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.Md5Checksum,
		&i.VideoCodec,
		&i.Width,
		&i.Height,
		&i.DurationSec,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
