// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explore.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listExploreCasts = `-- name: ListExploreCasts :many
SELECT 
    c.id, 
    c.name, 
    c.original_name,
    c.profile_path,
    c.known_for_department,
    COALESCE(c.views, 0)::bigint AS views
FROM casts c
WHERE c.active = true
ORDER BY c.views DESC, c.name ASC
LIMIT $1 OFFSET $2
`

type ListExploreCastsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListExploreCastsRow struct {
	ID                 int64       `json:"id"`
	Name               string      `json:"name"`
	OriginalName       pgtype.Text `json:"original_name"`
	ProfilePath        pgtype.Text `json:"profile_path"`
	KnownForDepartment pgtype.Text `json:"known_for_department"`
	Views              int64       `json:"views"`
}

func (q *Queries) ListExploreCasts(ctx context.Context, arg ListExploreCastsParams) ([]ListExploreCastsRow, error) {
	rows, err := q.db.Query(ctx, listExploreCasts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreCastsRow
	for rows.Next() {
		var i ListExploreCastsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginalName,
			&i.ProfilePath,
			&i.KnownForDepartment,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExploreCollections = `-- name: ListExploreCollections :many
SELECT 
    c.id, 
    c.slug, 
    COALESCE(c.name_lat, c.original_name) AS title, 
    c.overview, 
    COALESCE((SELECT file_path FROM media_images WHERE collection_id = c.id AND type = 'poster' AND is_main = true LIMIT 1), c.poster_path) AS poster_path,
    COALESCE((SELECT file_path FROM media_images WHERE collection_id = c.id AND type = 'backdrop' AND is_main = true LIMIT 1), c.backdrop_path) AS backdrop_path
FROM collections c
ORDER BY c.original_name ASC
LIMIT $1 OFFSET $2
`

type ListExploreCollectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListExploreCollectionsRow struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
}

func (q *Queries) ListExploreCollections(ctx context.Context, arg ListExploreCollectionsParams) ([]ListExploreCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listExploreCollections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreCollectionsRow
	for rows.Next() {
		var i ListExploreCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.BackdropPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExploreCountries = `-- name: ListExploreCountries :many
SELECT 
    c.id, 
    c.name, 
    c.iso_3166_1, 
    c.logo_path
FROM countries c
ORDER BY c.name ASC
LIMIT $1 OFFSET $2
`

type ListExploreCountriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListExploreCountriesRow struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	Iso31661 string      `json:"iso_3166_1"`
	LogoPath pgtype.Text `json:"logo_path"`
}

func (q *Queries) ListExploreCountries(ctx context.Context, arg ListExploreCountriesParams) ([]ListExploreCountriesRow, error) {
	rows, err := q.db.Query(ctx, listExploreCountries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreCountriesRow
	for rows.Next() {
		var i ListExploreCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso31661,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExploreNetworks = `-- name: ListExploreNetworks :many
SELECT 
    n.id, 
    n.slug, 
    n.name, 
    n.poster_path, 
    n.backdrop_path
FROM networks n
ORDER BY n.sort_order ASC, n.name ASC
LIMIT $1 OFFSET $2
`

type ListExploreNetworksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListExploreNetworksRow struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
}

func (q *Queries) ListExploreNetworks(ctx context.Context, arg ListExploreNetworksParams) ([]ListExploreNetworksRow, error) {
	rows, err := q.db.Query(ctx, listExploreNetworks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreNetworksRow
	for rows.Next() {
		var i ListExploreNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PosterPath,
			&i.BackdropPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
