// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explore_genres.sql

package db

import (
	"context"
)

const listExploreGenres = `-- name: ListExploreGenres :many
SELECT id, COALESCE(name_esp, name_eng)::varchar AS name, slug 
FROM genres 
ORDER BY name ASC
`

type ListExploreGenresRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) ListExploreGenres(ctx context.Context) ([]ListExploreGenresRow, error) {
	rows, err := q.db.Query(ctx, listExploreGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreGenresRow
	for rows.Next() {
		var i ListExploreGenresRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
