// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jellyfin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJellyfinPlanRule = `-- name: CreateJellyfinPlanRule :one
INSERT INTO jellyfin.plan_rules (
    plan_id, jellyfin_server_id, libraries
) VALUES (
    $1, $2, $3
)
RETURNING id, plan_id, jellyfin_server_id, libraries, created_at, updated_at
`

type CreateJellyfinPlanRuleParams struct {
	PlanID           int64  `json:"plan_id"`
	JellyfinServerID int64  `json:"jellyfin_server_id"`
	Libraries        []byte `json:"libraries"`
}

func (q *Queries) CreateJellyfinPlanRule(ctx context.Context, arg CreateJellyfinPlanRuleParams) (JellyfinPlanRule, error) {
	row := q.db.QueryRow(ctx, createJellyfinPlanRule, arg.PlanID, arg.JellyfinServerID, arg.Libraries)
	var i JellyfinPlanRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.JellyfinServerID,
		&i.Libraries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJellyfinServer = `-- name: CreateJellyfinServer :one
INSERT INTO jellyfin.servers (
    name, url, api_key, auto_provision, active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, url, api_key, auto_provision, active, created_at, updated_at
`

type CreateJellyfinServerParams struct {
	Name          string `json:"name"`
	Url           string `json:"url"`
	ApiKey        string `json:"api_key"`
	AutoProvision bool   `json:"auto_provision"`
	Active        bool   `json:"active"`
}

func (q *Queries) CreateJellyfinServer(ctx context.Context, arg CreateJellyfinServerParams) (JellyfinServer, error) {
	row := q.db.QueryRow(ctx, createJellyfinServer,
		arg.Name,
		arg.Url,
		arg.ApiKey,
		arg.AutoProvision,
		arg.Active,
	)
	var i JellyfinServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ApiKey,
		&i.AutoProvision,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJellyfinUser = `-- name: CreateJellyfinUser :one
INSERT INTO jellyfin.users (
    user_id, jellyfin_server_id, jellyfin_internal_id, jellyfin_username, sync_status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, jellyfin_server_id, jellyfin_internal_id, jellyfin_username, sync_status, created_at, updated_at
`

type CreateJellyfinUserParams struct {
	UserID             int64       `json:"user_id"`
	JellyfinServerID   int64       `json:"jellyfin_server_id"`
	JellyfinInternalID pgtype.UUID `json:"jellyfin_internal_id"`
	JellyfinUsername   pgtype.Text `json:"jellyfin_username"`
	SyncStatus         string      `json:"sync_status"`
}

func (q *Queries) CreateJellyfinUser(ctx context.Context, arg CreateJellyfinUserParams) (JellyfinUser, error) {
	row := q.db.QueryRow(ctx, createJellyfinUser,
		arg.UserID,
		arg.JellyfinServerID,
		arg.JellyfinInternalID,
		arg.JellyfinUsername,
		arg.SyncStatus,
	)
	var i JellyfinUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JellyfinServerID,
		&i.JellyfinInternalID,
		&i.JellyfinUsername,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJellyfinUsersForServer = `-- name: GetJellyfinUsersForServer :many
SELECT id, user_id, jellyfin_server_id, jellyfin_internal_id, jellyfin_username, sync_status, created_at, updated_at FROM jellyfin.users
WHERE jellyfin_server_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetJellyfinUsersForServer(ctx context.Context, jellyfinServerID int64) ([]JellyfinUser, error) {
	rows, err := q.db.Query(ctx, getJellyfinUsersForServer, jellyfinServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JellyfinUser
	for rows.Next() {
		var i JellyfinUser
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JellyfinServerID,
			&i.JellyfinInternalID,
			&i.JellyfinUsername,
			&i.SyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanRulesForServer = `-- name: GetPlanRulesForServer :many
SELECT id, plan_id, jellyfin_server_id, libraries, created_at, updated_at FROM jellyfin.plan_rules
WHERE jellyfin_server_id = $1
`

func (q *Queries) GetPlanRulesForServer(ctx context.Context, jellyfinServerID int64) ([]JellyfinPlanRule, error) {
	rows, err := q.db.Query(ctx, getPlanRulesForServer, jellyfinServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JellyfinPlanRule
	for rows.Next() {
		var i JellyfinPlanRule
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.JellyfinServerID,
			&i.Libraries,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveJellyfinServers = `-- name: ListActiveJellyfinServers :many
SELECT id, name, url, api_key, auto_provision, active, created_at, updated_at FROM jellyfin.servers
WHERE active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveJellyfinServers(ctx context.Context) ([]JellyfinServer, error) {
	rows, err := q.db.Query(ctx, listActiveJellyfinServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JellyfinServer
	for rows.Next() {
		var i JellyfinServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.ApiKey,
			&i.AutoProvision,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
