// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMediaImages = `-- name: GetMediaImages :many
SELECT id, movie_id, serie_id, season_id, episode_id, collection_id, file_path, type, source, language_iso, is_main, created_at FROM media_images
WHERE 
  (movie_id = $1 OR $1 IS NULL) AND
  (serie_id = $2 OR $2 IS NULL) AND
  (season_id = $3 OR $3 IS NULL) AND
  (episode_id = $4 OR $4 IS NULL) AND
  (collection_id = $5 OR $5 IS NULL)
`

type GetMediaImagesParams struct {
	MovieID      pgtype.Int8 `json:"movie_id"`
	SerieID      pgtype.Int8 `json:"serie_id"`
	SeasonID     pgtype.Int8 `json:"season_id"`
	EpisodeID    pgtype.Int8 `json:"episode_id"`
	CollectionID pgtype.Int8 `json:"collection_id"`
}

func (q *Queries) GetMediaImages(ctx context.Context, arg GetMediaImagesParams) ([]MediaImage, error) {
	rows, err := q.db.Query(ctx, getMediaImages,
		arg.MovieID,
		arg.SerieID,
		arg.SeasonID,
		arg.EpisodeID,
		arg.CollectionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaImage
	for rows.Next() {
		var i MediaImage
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.SerieID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.CollectionID,
			&i.FilePath,
			&i.Type,
			&i.Source,
			&i.LanguageIso,
			&i.IsMain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMediaImage = `-- name: InsertMediaImage :one
INSERT INTO media_images (
  movie_id, serie_id, season_id, episode_id, collection_id,
  file_path, type, source, language_iso, is_main
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id
`

type InsertMediaImageParams struct {
	MovieID      pgtype.Int8 `json:"movie_id"`
	SerieID      pgtype.Int8 `json:"serie_id"`
	SeasonID     pgtype.Int8 `json:"season_id"`
	EpisodeID    pgtype.Int8 `json:"episode_id"`
	CollectionID pgtype.Int8 `json:"collection_id"`
	FilePath     string      `json:"file_path"`
	Type         string      `json:"type"`
	Source       string      `json:"source"`
	LanguageIso  pgtype.Text `json:"language_iso"`
	IsMain       bool        `json:"is_main"`
}

func (q *Queries) InsertMediaImage(ctx context.Context, arg InsertMediaImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMediaImage,
		arg.MovieID,
		arg.SerieID,
		arg.SeasonID,
		arg.EpisodeID,
		arg.CollectionID,
		arg.FilePath,
		arg.Type,
		arg.Source,
		arg.LanguageIso,
		arg.IsMain,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setMainMediaImage = `-- name: SetMainMediaImage :exec
UPDATE media_images SET is_main = true WHERE id = $1
`

func (q *Queries) SetMainMediaImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setMainMediaImage, id)
	return err
}

const unsetMainMediaImages = `-- name: UnsetMainMediaImages :exec
UPDATE media_images SET is_main = false WHERE type = $1 AND (
  (movie_id = $2 AND $2 IS NOT NULL) OR
  (serie_id = $3 AND $3 IS NOT NULL) OR
  (season_id = $4 AND $4 IS NOT NULL) OR
  (episode_id = $5 AND $5 IS NOT NULL)
)
`

type UnsetMainMediaImagesParams struct {
	Type      string      `json:"type"`
	MovieID   pgtype.Int8 `json:"movie_id"`
	SerieID   pgtype.Int8 `json:"serie_id"`
	SeasonID  pgtype.Int8 `json:"season_id"`
	EpisodeID pgtype.Int8 `json:"episode_id"`
}

func (q *Queries) UnsetMainMediaImages(ctx context.Context, arg UnsetMainMediaImagesParams) error {
	_, err := q.db.Exec(ctx, unsetMainMediaImages,
		arg.Type,
		arg.MovieID,
		arg.SerieID,
		arg.SeasonID,
		arg.EpisodeID,
	)
	return err
}
