// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BillingPlan struct {
	ID                 int64              `json:"id"`
	Key                string             `json:"key"`
	Category           string             `json:"category"`
	Name               string             `json:"name"`
	Color              string             `json:"color"`
	Priority           int16              `json:"priority"`
	Badge              pgtype.Text        `json:"badge"`
	IsFeatured         bool               `json:"is_featured"`
	MaxProfiles        int16              `json:"max_profiles"`
	MaxDevices         int16              `json:"max_devices"`
	MaxPendingRequests int16              `json:"max_pending_requests"`
	ParentalControl    bool               `json:"parental_control"`
	Features           []byte             `json:"features"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type BillingPlanPrice struct {
	ID         int64              `json:"id"`
	PlanID     int64              `json:"plan_id"`
	Currency   string             `json:"currency"`
	PriceCents int32              `json:"price_cents"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type BillingSubscription struct {
	ID               int64              `json:"id"`
	UserID           pgtype.Int8        `json:"user_id"`
	PlanID           int64              `json:"plan_id"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	RenewsAt         pgtype.Timestamptz `json:"renews_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	CanceledAt       pgtype.Timestamptz `json:"canceled_at"`
	PlanKeySnapshot  pgtype.Text        `json:"plan_key_snapshot"`
	PlanNameSnapshot pgtype.Text        `json:"plan_name_snapshot"`
	CurrencyPaid     pgtype.Text        `json:"currency_paid"`
	PricePaidCents   pgtype.Int4        `json:"price_paid_cents"`
	Meta             []byte             `json:"meta"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Cast struct {
	ID                 int64              `json:"id"`
	TmdbID             pgtype.Int8        `json:"tmdb_id"`
	TvdbID             pgtype.Int8        `json:"tvdb_id"`
	Uuid               pgtype.UUID        `json:"uuid"`
	Name               string             `json:"name"`
	OriginalName       pgtype.Text        `json:"original_name"`
	Gender             pgtype.Int2        `json:"gender"`
	PlaceOfBirth       pgtype.Text        `json:"place_of_birth"`
	ProfilePath        pgtype.Text        `json:"profile_path"`
	ImdbID             pgtype.Text        `json:"imdb_id"`
	KnownForDepartment pgtype.Text        `json:"known_for_department"`
	Biography          pgtype.Text        `json:"biography"`
	Adult              bool               `json:"adult"`
	Birthday           pgtype.Date        `json:"birthday"`
	Deathday           pgtype.Date        `json:"deathday"`
	Views              int64              `json:"views"`
	Active             bool               `json:"active"`
	SearchVector       interface{}        `json:"search_vector"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Collection struct {
	ID           int64              `json:"id"`
	TmdbID       pgtype.Int8        `json:"tmdb_id"`
	TvdbID       pgtype.Int8        `json:"tvdb_id"`
	Uuid         pgtype.UUID        `json:"uuid"`
	OriginalName string             `json:"original_name"`
	Slug         string             `json:"slug"`
	NameLat      pgtype.Text        `json:"name_lat"`
	NameEsp      pgtype.Text        `json:"name_esp"`
	NameEng      pgtype.Text        `json:"name_eng"`
	Overview     pgtype.Text        `json:"overview"`
	PosterPath   pgtype.Text        `json:"poster_path"`
	BackdropPath pgtype.Text        `json:"backdrop_path"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Country struct {
	ID          int64              `json:"id"`
	Uuid        pgtype.UUID        `json:"uuid"`
	Name        string             `json:"name"`
	EnglishName pgtype.Text        `json:"english_name"`
	Iso31661    string             `json:"iso_3166_1"`
	LogoPath    pgtype.Text        `json:"logo_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	ActiveProfileID pgtype.Int8        `json:"active_profile_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	Name            pgtype.Text        `json:"name"`
	Platform        string             `json:"platform"`
	Fingerprint     string             `json:"fingerprint"`
	AppVersion      pgtype.Text        `json:"app_version"`
	DeviceBrand     pgtype.Text        `json:"device_brand"`
	DeviceModel     pgtype.Text        `json:"device_model"`
	OsVersion       pgtype.Text        `json:"os_version"`
	LastIp          *netip.Addr        `json:"last_ip"`
	LastUserAgent   pgtype.Text        `json:"last_user_agent"`
	FirstLoginAt    pgtype.Timestamptz `json:"first_login_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveItem struct {
	ID          int64              `json:"id"`
	SourceID    pgtype.Int8        `json:"source_id"`
	RemoteID    string             `json:"remote_id"`
	Name        string             `json:"name"`
	MimeType    pgtype.Text        `json:"mime_type"`
	SizeBytes   pgtype.Int8        `json:"size_bytes"`
	Md5Checksum pgtype.Text        `json:"md5_checksum"`
	VideoCodec  pgtype.Text        `json:"video_codec"`
	Width       pgtype.Int4        `json:"width"`
	Height      pgtype.Int4        `json:"height"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DriveReplica struct {
	ID                int64              `json:"id"`
	ServiceAccountID  pgtype.Int8        `json:"service_account_id"`
	Name              string             `json:"name"`
	SharedDriveID     string             `json:"shared_drive_id"`
	StreamingFolderID pgtype.Text        `json:"streaming_folder_id"`
	GemdriveFolderID  pgtype.Text        `json:"gemdrive_folder_id"`
	RecoveryFolderID  pgtype.Text        `json:"recovery_folder_id"`
	SpaceLimitGib     pgtype.Int4        `json:"space_limit_gib"`
	Priority          pgtype.Int4        `json:"priority"`
	HealthStatus      pgtype.Text        `json:"health_status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DriveServiceAccount struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Provider        string             `json:"provider"`
	CredentialsJson string             `json:"credentials_json"`
	QuotaLimitBytes pgtype.Int8        `json:"quota_limit_bytes"`
	QuotaUsedBytes  pgtype.Int8        `json:"quota_used_bytes"`
	IsActive        pgtype.Bool        `json:"is_active"`
	Status          pgtype.Text        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveSource struct {
	ID                  int64              `json:"id"`
	ServiceAccountID    pgtype.Int8        `json:"service_account_id"`
	Name                string             `json:"name"`
	FolderID            string             `json:"folder_id"`
	Provider            string             `json:"provider"`
	SyncIntervalMinutes pgtype.Int4        `json:"sync_interval_minutes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type DriveSyncRun struct {
	ID           int64              `json:"id"`
	SourceID     pgtype.Int8        `json:"source_id"`
	SyncSession  string             `json:"sync_session"`
	Status       string             `json:"status"`
	FilesFound   pgtype.Int4        `json:"files_found"`
	ItemsCreated pgtype.Int4        `json:"items_created"`
	ItemsUpdated pgtype.Int4        `json:"items_updated"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type Favorite struct {
	ID        int64              `json:"id"`
	ProfileID int64              `json:"profile_id"`
	MovieID   pgtype.Int8        `json:"movie_id"`
	SerieID   pgtype.Int8        `json:"serie_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Genre struct {
	ID        int64              `json:"id"`
	TmdbID    pgtype.Int8        `json:"tmdb_id"`
	TvdbID    pgtype.Int8        `json:"tvdb_id"`
	NameEng   string             `json:"name_eng"`
	NameEsp   pgtype.Text        `json:"name_esp"`
	Slug      string             `json:"slug"`
	ImagePath pgtype.Text        `json:"image_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type JellyfinPlanRule struct {
	ID               int64              `json:"id"`
	PlanID           int64              `json:"plan_id"`
	JellyfinServerID int64              `json:"jellyfin_server_id"`
	Libraries        []byte             `json:"libraries"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type JellyfinServer struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	ApiKey        string             `json:"api_key"`
	AutoProvision bool               `json:"auto_provision"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type JellyfinUser struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	JellyfinServerID   int64              `json:"jellyfin_server_id"`
	JellyfinInternalID pgtype.UUID        `json:"jellyfin_internal_id"`
	JellyfinUsername   pgtype.Text        `json:"jellyfin_username"`
	SyncStatus         string             `json:"sync_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type LoginCode struct {
	ID                 int64              `json:"id"`
	Code               string             `json:"code"`
	PairTokenHash      string             `json:"pair_token_hash"`
	UserID             pgtype.Int8        `json:"user_id"`
	DeviceID           pgtype.Int8        `json:"device_id"`
	ApprovedByDeviceID pgtype.Int8        `json:"approved_by_device_id"`
	UsedAt             pgtype.Timestamptz `json:"used_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type MediaAudioTrack struct {
	ID            int64              `json:"id"`
	MediaSourceID int64              `json:"media_source_id"`
	TrackNo       int16              `json:"track_no"`
	Lang          pgtype.Text        `json:"lang"`
	Codec         pgtype.Text        `json:"codec"`
	ChannelLayout pgtype.Text        `json:"channel_layout"`
	BitrateKbps   pgtype.Int2        `json:"bitrate_kbps"`
	SampleRateHz  pgtype.Int4        `json:"sample_rate_hz"`
	IsDefault     bool               `json:"is_default"`
	Title         pgtype.Text        `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MediaImage struct {
	ID           int64              `json:"id"`
	MovieID      pgtype.Int8        `json:"movie_id"`
	SerieID      pgtype.Int8        `json:"serie_id"`
	SeasonID     pgtype.Int8        `json:"season_id"`
	EpisodeID    pgtype.Int8        `json:"episode_id"`
	CollectionID pgtype.Int8        `json:"collection_id"`
	FilePath     string             `json:"file_path"`
	Type         string             `json:"type"`
	Source       string             `json:"source"`
	LanguageIso  pgtype.Text        `json:"language_iso"`
	IsMain       bool               `json:"is_main"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MediaPlaybackSession struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	MediaSourceID int64              `json:"media_source_id"`
	DeviceID      pgtype.Int8        `json:"device_id"`
	IpAddress     *netip.Addr        `json:"ip_address"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastPingAt    pgtype.Timestamptz `json:"last_ping_at"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MediaReport struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	MediaType string             `json:"media_type"`
	MediaID   int64              `json:"media_id"`
	Reason    string             `json:"reason"`
	Details   pgtype.Text        `json:"details"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MediaRequest struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TmdbID    pgtype.Int4        `json:"tmdb_id"`
	Title     string             `json:"title"`
	MediaType string             `json:"media_type"`
	Status    string             `json:"status"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MediaSource struct {
	ID            int64              `json:"id"`
	ProviderID    pgtype.Int8        `json:"provider_id"`
	MovieID       pgtype.Int8        `json:"movie_id"`
	EpisodeID     pgtype.Int8        `json:"episode_id"`
	Label         pgtype.Text        `json:"label"`
	Quality       pgtype.Text        `json:"quality"`
	Link          string             `json:"link"`
	LinkHash      pgtype.Text        `json:"link_hash"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	DurationSec   pgtype.Int4        `json:"duration_sec"`
	VideoCodec    pgtype.Text        `json:"video_codec"`
	AudioChannels pgtype.Text        `json:"audio_channels"`
	DynamicRange  pgtype.Text        `json:"dynamic_range"`
	BitDepth      pgtype.Int2        `json:"bit_depth"`
	RecapStart    int32              `json:"recap_start"`
	RecapEnd      int32              `json:"recap_end"`
	OpeningStart  int32              `json:"opening_start"`
	OpeningEnd    int32              `json:"opening_end"`
	EndingStart   int32              `json:"ending_start"`
	EndingEnd     int32              `json:"ending_end"`
	Status        bool               `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Type          string             `json:"type"`
}

type MediaSubtitleTrack struct {
	ID            int64              `json:"id"`
	MediaSourceID int64              `json:"media_source_id"`
	TrackNo       int16              `json:"track_no"`
	Lang          pgtype.Text        `json:"lang"`
	Type          pgtype.Text        `json:"type"`
	Embedded      bool               `json:"embedded"`
	Link          pgtype.Text        `json:"link"`
	LinkHash      pgtype.Text        `json:"link_hash"`
	Zip           bool               `json:"zip"`
	Forced        bool               `json:"forced"`
	Cc            bool               `json:"cc"`
	IsDefault     bool               `json:"is_default"`
	Title         pgtype.Text        `json:"title"`
	Status        bool               `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Movie struct {
	ID              int64              `json:"id"`
	Uuid            pgtype.UUID        `json:"uuid"`
	Slug            string             `json:"slug"`
	TmdbID          pgtype.Int8        `json:"tmdb_id"`
	TvdbID          pgtype.Int8        `json:"tvdb_id"`
	ImdbID          pgtype.Text        `json:"imdb_id"`
	IsType          string             `json:"is_type"`
	OriginalName    string             `json:"original_name"`
	TitleLat        pgtype.Text        `json:"title_lat"`
	TitleEsp        pgtype.Text        `json:"title_esp"`
	TitleEng        pgtype.Text        `json:"title_eng"`
	Overview        pgtype.Text        `json:"overview"`
	TrailerKey      pgtype.Text        `json:"trailer_key"`
	ReleaseDate     pgtype.Date        `json:"release_date"`
	Runtime         pgtype.Int2        `json:"runtime"`
	PosterPath      pgtype.Text        `json:"poster_path"`
	BackdropPath    pgtype.Text        `json:"backdrop_path"`
	Certification   pgtype.Text        `json:"certification"`
	VoteAverage     pgtype.Numeric     `json:"vote_average"`
	VoteCount       int64              `json:"vote_count"`
	VoteGf          int64              `json:"vote_gf"`
	Views           int64              `json:"views"`
	Premiere        bool               `json:"premiere"`
	Upcoming        bool               `json:"upcoming"`
	Premium         bool               `json:"premium"`
	Active          bool               `json:"active"`
	EnableStream    bool               `json:"enable_stream"`
	EnableDownload  bool               `json:"enable_download"`
	EnableAdsUnlock bool               `json:"enable_ads_unlock"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MovieCast struct {
	MovieID       int64       `json:"movie_id"`
	CastID        int64       `json:"cast_id"`
	CharacterName pgtype.Text `json:"character_name"`
	Job           pgtype.Text `json:"job"`
	SortOrder     int16       `json:"sort_order"`
}

type MovieCollection struct {
	MovieID      int64 `json:"movie_id"`
	CollectionID int64 `json:"collection_id"`
}

type MovieCountry struct {
	MovieID   int64 `json:"movie_id"`
	CountryID int64 `json:"country_id"`
}

type MovieGenre struct {
	MovieID int64 `json:"movie_id"`
	GenreID int64 `json:"genre_id"`
}

type MovieNetwork struct {
	MovieID   int64 `json:"movie_id"`
	NetworkID int64 `json:"network_id"`
}

type Network struct {
	ID           int64              `json:"id"`
	TmdbID       pgtype.Int8        `json:"tmdb_id"`
	TvdbID       pgtype.Int8        `json:"tvdb_id"`
	Uuid         pgtype.UUID        `json:"uuid"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	PosterPath   pgtype.Text        `json:"poster_path"`
	BackdropPath pgtype.Text        `json:"backdrop_path"`
	SortOrder    int16              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OauthProvider struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    pgtype.Text        `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	GroupName   string             `json:"group_name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PersonalAccessToken struct {
	ID            int64              `json:"id"`
	TokenableType string             `json:"tokenable_type"`
	TokenableID   int64              `json:"tokenable_id"`
	Name          string             `json:"name"`
	Client        pgtype.Text        `json:"client"`
	DeviceID      pgtype.Int8        `json:"device_id"`
	Token         string             `json:"token"`
	Abilities     pgtype.Text        `json:"abilities"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	Name              string             `json:"name"`
	Active            bool               `json:"active"`
	PinEnabled        bool               `json:"pin_enabled"`
	PinHash           pgtype.Text        `json:"pin_hash"`
	PinFailedAttempts int16              `json:"pin_failed_attempts"`
	PinLockedUntil    pgtype.Timestamptz `json:"pin_locked_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ProfileParentalControl struct {
	ID                 int64              `json:"id"`
	ProfileID          int64              `json:"profile_id"`
	Enabled            bool               `json:"enabled"`
	MaxMovieRatingCode pgtype.Text        `json:"max_movie_rating_code"`
	MaxTvRatingCode    pgtype.Text        `json:"max_tv_rating_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Provider struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Type      string             `json:"type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64              `json:"role_id"`
	PermissionID int64              `json:"permission_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
}

type SerieCast struct {
	SerieID       int64       `json:"serie_id"`
	CastID        int64       `json:"cast_id"`
	CharacterName pgtype.Text `json:"character_name"`
	Job           pgtype.Text `json:"job"`
	SortOrder     int16       `json:"sort_order"`
}

type SerieCountry struct {
	SerieID   int64 `json:"serie_id"`
	CountryID int64 `json:"country_id"`
}

type SerieEpisode struct {
	ID              int64              `json:"id"`
	TmdbID          pgtype.Int8        `json:"tmdb_id"`
	TvdbID          pgtype.Int8        `json:"tvdb_id"`
	SeasonID        int64              `json:"season_id"`
	EpisodeNumber   int16              `json:"episode_number"`
	Name            string             `json:"name"`
	Overview        pgtype.Text        `json:"overview"`
	StillPath       pgtype.Text        `json:"still_path"`
	StillPathTv     pgtype.Text        `json:"still_path_tv"`
	VoteAverage     pgtype.Numeric     `json:"vote_average"`
	VoteCount       int64              `json:"vote_count"`
	Views           int64              `json:"views"`
	AirDate         pgtype.Date        `json:"air_date"`
	EnableStream    bool               `json:"enable_stream"`
	EnableDownload  bool               `json:"enable_download"`
	EnableAdsUnlock bool               `json:"enable_ads_unlock"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SerieGenre struct {
	SerieID int64 `json:"serie_id"`
	GenreID int64 `json:"genre_id"`
}

type SerieNetwork struct {
	SerieID   int64 `json:"serie_id"`
	NetworkID int64 `json:"network_id"`
}

type SerieSeason struct {
	ID           int64              `json:"id"`
	TmdbID       pgtype.Int8        `json:"tmdb_id"`
	TvdbID       pgtype.Int8        `json:"tvdb_id"`
	SerieID      int64              `json:"serie_id"`
	SeasonNumber int16              `json:"season_number"`
	Name         string             `json:"name"`
	Overview     pgtype.Text        `json:"overview"`
	PosterPath   pgtype.Text        `json:"poster_path"`
	AirDate      pgtype.Date        `json:"air_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Series struct {
	ID             int64              `json:"id"`
	Uuid           pgtype.UUID        `json:"uuid"`
	Slug           string             `json:"slug"`
	TmdbID         pgtype.Int8        `json:"tmdb_id"`
	TvdbID         pgtype.Int8        `json:"tvdb_id"`
	ImdbID         pgtype.Text        `json:"imdb_id"`
	IsType         string             `json:"is_type"`
	OriginalName   string             `json:"original_name"`
	TitleLat       pgtype.Text        `json:"title_lat"`
	TitleEsp       pgtype.Text        `json:"title_esp"`
	TitleEng       pgtype.Text        `json:"title_eng"`
	Overview       pgtype.Text        `json:"overview"`
	TrailerKey     pgtype.Text        `json:"trailer_key"`
	FirstAirDate   pgtype.Date        `json:"first_air_date"`
	EpisodeRunTime pgtype.Int2        `json:"episode_run_time"`
	PosterPath     pgtype.Text        `json:"poster_path"`
	BackdropPath   pgtype.Text        `json:"backdrop_path"`
	Certification  pgtype.Text        `json:"certification"`
	VoteAverage    pgtype.Numeric     `json:"vote_average"`
	VoteCount      int64              `json:"vote_count"`
	VoteGf         int64              `json:"vote_gf"`
	Views          int64              `json:"views"`
	Premiere       bool               `json:"premiere"`
	Upcoming       bool               `json:"upcoming"`
	Premium        bool               `json:"premium"`
	Active         bool               `json:"active"`
	SearchVector   interface{}        `json:"search_vector"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	RememberToken     pgtype.Text        `json:"remember_token"`
	LastVipWinAt      pgtype.Timestamptz `json:"last_vip_win_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	ReactivatedAt     pgtype.Timestamptz `json:"reactivated_at"`
	ReactivationCount int32              `json:"reactivation_count"`
	Xp                int32              `json:"xp"`
	CurrentStreak     int32              `json:"current_streak"`
	LongestStreak     int32              `json:"longest_streak"`
	IsShadowbanned    bool               `json:"is_shadowbanned"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	UserID     int64              `json:"user_id"`
	RoleID     int64              `json:"role_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type WatchProgress struct {
	ID              int64              `json:"id"`
	ProfileID       int64              `json:"profile_id"`
	MovieID         pgtype.Int8        `json:"movie_id"`
	EpisodeID       pgtype.Int8        `json:"episode_id"`
	ProgressSeconds int32              `json:"progress_seconds"`
	TotalSeconds    int32              `json:"total_seconds"`
	Percentage      int16              `json:"percentage"`
	Completed       bool               `json:"completed"`
	LastWatchedAt   pgtype.Timestamptz `json:"last_watched_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
