// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContinueWatching = `-- name: GetContinueWatching :many
SELECT 
    wp.id, wp.profile_id, wp.content_id, wp.progress_sec, wp.is_completed,
    COALESCE(m.slug, s.slug) AS slug,
    COALESCE(m.title_lat, m.original_name, s.title_lat, s.original_name) AS title,
    COALESCE(m.backdrop_path, s.backdrop_path) AS backdrop_path,
    COALESCE(m.poster_path, s.poster_path) AS poster_path,
    COALESCE(m.poster_path_tv, s.poster_path_tv) AS poster_path_tv,
    COALESCE(m.logo_path, s.logo_path) AS logo_path
FROM watch_progress wp
LEFT JOIN movies m ON wp.content_type = 'movie' AND wp.content_id = m.id
LEFT JOIN serie_episodes ep ON wp.content_type = 'episode' AND wp.content_id = ep.id
LEFT JOIN series s ON ep.serie_id = s.id
WHERE wp.profile_id = $1 AND wp.is_completed = false
ORDER BY wp.last_watched_at DESC LIMIT 20
`

type GetContinueWatchingRow struct {
	ID           int64       `json:"id"`
	ProfileID    int64       `json:"profile_id"`
	ContentID    int64       `json:"content_id"`
	ProgressSec  int32       `json:"progress_sec"`
	IsCompleted  bool        `json:"is_completed"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	LogoPath     pgtype.Text `json:"logo_path"`
}

func (q *Queries) GetContinueWatching(ctx context.Context, profileID int64) ([]GetContinueWatchingRow, error) {
	rows, err := q.db.Query(ctx, getContinueWatching, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContinueWatchingRow
	for rows.Next() {
		var i GetContinueWatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ContentID,
			&i.ProgressSec,
			&i.IsCompleted,
			&i.Slug,
			&i.Title,
			&i.BackdropPath,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyListMovies = `-- name: GetMyListMovies :many
SELECT m.id, m.slug, COALESCE(m.title_lat, m.original_name) AS title, m.overview, m.poster_path, m.poster_path_tv, m.backdrop_path, m.logo_path
FROM favorites f
JOIN movies m ON f.content_type = 'movie' AND f.content_id = m.id
WHERE f.profile_id = $1
ORDER BY f.created_at DESC LIMIT 20
`

type GetMyListMoviesRow struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
}

func (q *Queries) GetMyListMovies(ctx context.Context, profileID int64) ([]GetMyListMoviesRow, error) {
	rows, err := q.db.Query(ctx, getMyListMovies, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyListMoviesRow
	for rows.Next() {
		var i GetMyListMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyListSeries = `-- name: GetMyListSeries :many
SELECT s.id, s.slug, COALESCE(s.title_lat, s.original_name) AS title, s.overview, s.poster_path, s.poster_path_tv, s.backdrop_path, s.logo_path
FROM favorites f
JOIN series s ON f.content_type = 'serie' AND f.content_id = s.id
WHERE f.profile_id = $1
ORDER BY f.created_at DESC LIMIT 20
`

type GetMyListSeriesRow struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
}

func (q *Queries) GetMyListSeries(ctx context.Context, profileID int64) ([]GetMyListSeriesRow, error) {
	rows, err := q.db.Query(ctx, getMyListSeries, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyListSeriesRow
	for rows.Next() {
		var i GetMyListSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayActiveNetworks = `-- name: GetPlayActiveNetworks :many
SELECT id, name, slug, poster_path, backdrop_path 
FROM networks 
ORDER BY sort_order ASC, name ASC LIMIT 20
`

type GetPlayActiveNetworksRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
}

func (q *Queries) GetPlayActiveNetworks(ctx context.Context) ([]GetPlayActiveNetworksRow, error) {
	rows, err := q.db.Query(ctx, getPlayActiveNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayActiveNetworksRow
	for rows.Next() {
		var i GetPlayActiveNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PosterPath,
			&i.BackdropPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayRecentAnimes = `-- name: GetPlayRecentAnimes :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    first_air_date
FROM series
WHERE active = true AND is_type = 'anime'
ORDER BY first_air_date DESC LIMIT 10
`

type GetPlayRecentAnimesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	FirstAirDate pgtype.Date `json:"first_air_date"`
}

func (q *Queries) GetPlayRecentAnimes(ctx context.Context) ([]GetPlayRecentAnimesRow, error) {
	rows, err := q.db.Query(ctx, getPlayRecentAnimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayRecentAnimesRow
	for rows.Next() {
		var i GetPlayRecentAnimesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.FirstAirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayRecentMovies = `-- name: GetPlayRecentMovies :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    release_date
FROM movies
WHERE active = true
ORDER BY release_date DESC LIMIT 10
`

type GetPlayRecentMoviesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	ReleaseDate  pgtype.Date `json:"release_date"`
}

func (q *Queries) GetPlayRecentMovies(ctx context.Context) ([]GetPlayRecentMoviesRow, error) {
	rows, err := q.db.Query(ctx, getPlayRecentMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayRecentMoviesRow
	for rows.Next() {
		var i GetPlayRecentMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayRecentSeries = `-- name: GetPlayRecentSeries :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    first_air_date
FROM series
WHERE active = true AND is_type = 'serie'
ORDER BY first_air_date DESC LIMIT 10
`

type GetPlayRecentSeriesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	FirstAirDate pgtype.Date `json:"first_air_date"`
}

func (q *Queries) GetPlayRecentSeries(ctx context.Context) ([]GetPlayRecentSeriesRow, error) {
	rows, err := q.db.Query(ctx, getPlayRecentSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayRecentSeriesRow
	for rows.Next() {
		var i GetPlayRecentSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.FirstAirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayTrendingAnimes = `-- name: GetPlayTrendingAnimes :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    COALESCE(views, 0)::bigint AS views
FROM series
WHERE active = true AND is_type = 'anime'
ORDER BY views DESC, vote_average DESC LIMIT 10
`

type GetPlayTrendingAnimesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	Views        int64       `json:"views"`
}

func (q *Queries) GetPlayTrendingAnimes(ctx context.Context) ([]GetPlayTrendingAnimesRow, error) {
	rows, err := q.db.Query(ctx, getPlayTrendingAnimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayTrendingAnimesRow
	for rows.Next() {
		var i GetPlayTrendingAnimesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayTrendingMovies = `-- name: GetPlayTrendingMovies :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = movies.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    COALESCE(views, 0)::bigint AS views
FROM movies
WHERE active = true
ORDER BY views DESC, vote_average DESC LIMIT 10
`

type GetPlayTrendingMoviesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	Views        int64       `json:"views"`
}

func (q *Queries) GetPlayTrendingMovies(ctx context.Context) ([]GetPlayTrendingMoviesRow, error) {
	rows, err := q.db.Query(ctx, getPlayTrendingMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayTrendingMoviesRow
	for rows.Next() {
		var i GetPlayTrendingMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayTrendingSeries = `-- name: GetPlayTrendingSeries :many
SELECT id, uuid, slug, COALESCE(title_lat, original_name) AS title, overview, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster' AND is_main = true LIMIT 1), poster_path) AS poster_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'poster_tv' AND is_main = true LIMIT 1), poster_path_tv) AS poster_path_tv,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'backdrop' AND is_main = true LIMIT 1), backdrop_path) AS backdrop_path, 
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = series.id AND type = 'logo' AND is_main = true LIMIT 1), logo_path) AS logo_path, 
    COALESCE(views, 0)::bigint AS views
FROM series
WHERE active = true AND is_type = 'serie'
ORDER BY views DESC, vote_average DESC LIMIT 10
`

type GetPlayTrendingSeriesRow struct {
	ID           int64       `json:"id"`
	Uuid         pgtype.UUID `json:"uuid"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	PosterPathTv pgtype.Text `json:"poster_path_tv"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	LogoPath     pgtype.Text `json:"logo_path"`
	Views        int64       `json:"views"`
}

func (q *Queries) GetPlayTrendingSeries(ctx context.Context) ([]GetPlayTrendingSeriesRow, error) {
	rows, err := q.db.Query(ctx, getPlayTrendingSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayTrendingSeriesRow
	for rows.Next() {
		var i GetPlayTrendingSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.PosterPathTv,
			&i.BackdropPath,
			&i.LogoPath,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
