// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPromoRedemption = `-- name: CheckPromoRedemption :one
SELECT id, user_id, promo_code_id, redeemed_at FROM promo_redemptions
WHERE user_id = $1 AND promo_code_id = $2
`

type CheckPromoRedemptionParams struct {
	UserID      int64 `json:"user_id"`
	PromoCodeID int64 `json:"promo_code_id"`
}

func (q *Queries) CheckPromoRedemption(ctx context.Context, arg CheckPromoRedemptionParams) (PromoRedemption, error) {
	row := q.db.QueryRow(ctx, checkPromoRedemption, arg.UserID, arg.PromoCodeID)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromoCodeID,
		&i.RedeemedAt,
	)
	return i, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (
    code, type, value, max_uses, valid_from, valid_until, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, code, type, value, max_uses, uses, valid_from, valid_until, is_active, created_at, updated_at
`

type CreatePromoCodeParams struct {
	Code       string             `json:"code"`
	Type       string             `json:"type"`
	Value      pgtype.Numeric     `json:"value"`
	MaxUses    pgtype.Int4        `json:"max_uses"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
	IsActive   bool               `json:"is_active"`
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.IsActive,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MaxUses,
		&i.Uses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromoCode = `-- name: DeletePromoCode :exec
DELETE FROM promo_codes WHERE id = $1
`

func (q *Queries) DeletePromoCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePromoCode, id)
	return err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, type, value, max_uses, uses, valid_from, valid_until, is_active, created_at, updated_at FROM promo_codes
WHERE code = $1
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MaxUses,
		&i.Uses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromoCodeByID = `-- name: GetPromoCodeByID :one
SELECT id, code, type, value, max_uses, uses, valid_from, valid_until, is_active, created_at, updated_at FROM promo_codes
WHERE id = $1
`

func (q *Queries) GetPromoCodeByID(ctx context.Context, id int64) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByID, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MaxUses,
		&i.Uses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPromoUses = `-- name: IncrementPromoUses :exec
UPDATE promo_codes
SET uses = uses + 1
WHERE id = $1
`

func (q *Queries) IncrementPromoUses(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPromoUses, id)
	return err
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, type, value, max_uses, uses, valid_from, valid_until, is_active, created_at, updated_at FROM promo_codes
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPromoCodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPromoCodes(ctx context.Context, arg ListPromoCodesParams) ([]PromoCode, error) {
	rows, err := q.db.Query(ctx, listPromoCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCode
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.MaxUses,
			&i.Uses,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPromoRedemption = `-- name: RecordPromoRedemption :one
INSERT INTO promo_redemptions (
    user_id, promo_code_id
) VALUES (
    $1, $2
) RETURNING id, user_id, promo_code_id, redeemed_at
`

type RecordPromoRedemptionParams struct {
	UserID      int64 `json:"user_id"`
	PromoCodeID int64 `json:"promo_code_id"`
}

func (q *Queries) RecordPromoRedemption(ctx context.Context, arg RecordPromoRedemptionParams) (PromoRedemption, error) {
	row := q.db.QueryRow(ctx, recordPromoRedemption, arg.UserID, arg.PromoCodeID)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromoCodeID,
		&i.RedeemedAt,
	)
	return i, err
}

const updatePromoCode = `-- name: UpdatePromoCode :one
UPDATE promo_codes
SET 
    code = coalesce($1, code),
    type = coalesce($2, type),
    value = coalesce($3, value),
    max_uses = coalesce($4, max_uses),
    valid_from = coalesce($5, valid_from),
    valid_until = coalesce($6, valid_until),
    is_active = coalesce($7, is_active),
    updated_at = NOW()
WHERE id = $8
RETURNING id, code, type, value, max_uses, uses, valid_from, valid_until, is_active, created_at, updated_at
`

type UpdatePromoCodeParams struct {
	Code       pgtype.Text        `json:"code"`
	Type       pgtype.Text        `json:"type"`
	Value      pgtype.Numeric     `json:"value"`
	MaxUses    pgtype.Int4        `json:"max_uses"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
	IsActive   pgtype.Bool        `json:"is_active"`
	ID         int64              `json:"id"`
}

func (q *Queries) UpdatePromoCode(ctx context.Context, arg UpdatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, updatePromoCode,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.IsActive,
		arg.ID,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MaxUses,
		&i.Uses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
