// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReferralsByDevice = `-- name: CountReferralsByDevice :one
SELECT COUNT(*) FROM referrals
WHERE device_id = $1
`

func (q *Queries) CountReferralsByDevice(ctx context.Context, deviceID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralsByDevice, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (
    referrer_user_id, device_id, attribution_hash, referee_user_id, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, referrer_user_id, device_id, attribution_hash, referee_user_id, promo_code_id, status, converted_at, rewarded_at, meta, created_at, updated_at
`

type CreateReferralParams struct {
	ReferrerUserID  pgtype.Int8 `json:"referrer_user_id"`
	DeviceID        pgtype.Int8 `json:"device_id"`
	AttributionHash pgtype.Text `json:"attribution_hash"`
	RefereeUserID   pgtype.Int8 `json:"referee_user_id"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral,
		arg.ReferrerUserID,
		arg.DeviceID,
		arg.AttributionHash,
		arg.RefereeUserID,
		arg.Status,
	)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerUserID,
		&i.DeviceID,
		&i.AttributionHash,
		&i.RefereeUserID,
		&i.PromoCodeID,
		&i.Status,
		&i.ConvertedAt,
		&i.RewardedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralByHash = `-- name: GetReferralByHash :one
SELECT id, referrer_user_id, device_id, attribution_hash, referee_user_id, promo_code_id, status, converted_at, rewarded_at, meta, created_at, updated_at FROM referrals
WHERE attribution_hash = $1
`

func (q *Queries) GetReferralByHash(ctx context.Context, attributionHash pgtype.Text) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByHash, attributionHash)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerUserID,
		&i.DeviceID,
		&i.AttributionHash,
		&i.RefereeUserID,
		&i.PromoCodeID,
		&i.Status,
		&i.ConvertedAt,
		&i.RewardedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralByReferee = `-- name: GetReferralByReferee :one
SELECT id, referrer_user_id, device_id, attribution_hash, referee_user_id, promo_code_id, status, converted_at, rewarded_at, meta, created_at, updated_at FROM referrals
WHERE referee_user_id = $1
`

func (q *Queries) GetReferralByReferee(ctx context.Context, refereeUserID pgtype.Int8) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferee, refereeUserID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerUserID,
		&i.DeviceID,
		&i.AttributionHash,
		&i.RefereeUserID,
		&i.PromoCodeID,
		&i.Status,
		&i.ConvertedAt,
		&i.RewardedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserReferrals = `-- name: ListUserReferrals :many
SELECT r.id, r.referrer_user_id, r.device_id, r.attribution_hash, r.referee_user_id, r.promo_code_id, r.status, r.converted_at, r.rewarded_at, r.meta, r.created_at, r.updated_at, u.name as referee_name, u.email as referee_email
FROM referrals r
LEFT JOIN users u ON r.referee_user_id = u.id
WHERE r.referrer_user_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserReferralsParams struct {
	ReferrerUserID pgtype.Int8 `json:"referrer_user_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListUserReferralsRow struct {
	ID              int64              `json:"id"`
	ReferrerUserID  pgtype.Int8        `json:"referrer_user_id"`
	DeviceID        pgtype.Int8        `json:"device_id"`
	AttributionHash pgtype.Text        `json:"attribution_hash"`
	RefereeUserID   pgtype.Int8        `json:"referee_user_id"`
	PromoCodeID     pgtype.Int8        `json:"promo_code_id"`
	Status          string             `json:"status"`
	ConvertedAt     pgtype.Timestamptz `json:"converted_at"`
	RewardedAt      pgtype.Timestamptz `json:"rewarded_at"`
	Meta            []byte             `json:"meta"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RefereeName     pgtype.Text        `json:"referee_name"`
	RefereeEmail    pgtype.Text        `json:"referee_email"`
}

func (q *Queries) ListUserReferrals(ctx context.Context, arg ListUserReferralsParams) ([]ListUserReferralsRow, error) {
	rows, err := q.db.Query(ctx, listUserReferrals, arg.ReferrerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserReferralsRow
	for rows.Next() {
		var i ListUserReferralsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerUserID,
			&i.DeviceID,
			&i.AttributionHash,
			&i.RefereeUserID,
			&i.PromoCodeID,
			&i.Status,
			&i.ConvertedAt,
			&i.RewardedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefereeName,
			&i.RefereeEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReferralStatus = `-- name: UpdateReferralStatus :one
UPDATE referrals
SET 
    status = $2,
    converted_at = CASE WHEN $2 = 'converted' THEN NOW() ELSE converted_at END,
    rewarded_at = CASE WHEN $2 = 'rewarded' THEN NOW() ELSE rewarded_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, referrer_user_id, device_id, attribution_hash, referee_user_id, promo_code_id, status, converted_at, rewarded_at, meta, created_at, updated_at
`

type UpdateReferralStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) (Referral, error) {
	row := q.db.QueryRow(ctx, updateReferralStatus, arg.ID, arg.Status)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerUserID,
		&i.DeviceID,
		&i.AttributionHash,
		&i.RefereeUserID,
		&i.PromoCodeID,
		&i.Status,
		&i.ConvertedAt,
		&i.RewardedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
