// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replicas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplica = `-- name: CreateReplica :one
INSERT INTO drive.replicas (
    service_account_id,
    name,
    shared_drive_id,
    streaming_folder_id,
    gemdrive_folder_id,
    recovery_folder_id,
    space_limit_gib,
    priority,
    health_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, service_account_id, name, shared_drive_id, streaming_folder_id, gemdrive_folder_id, recovery_folder_id, space_limit_gib, priority, health_status, created_at, updated_at
`

type CreateReplicaParams struct {
	ServiceAccountID  pgtype.Int8 `json:"service_account_id"`
	Name              string      `json:"name"`
	SharedDriveID     string      `json:"shared_drive_id"`
	StreamingFolderID pgtype.Text `json:"streaming_folder_id"`
	GemdriveFolderID  pgtype.Text `json:"gemdrive_folder_id"`
	RecoveryFolderID  pgtype.Text `json:"recovery_folder_id"`
	SpaceLimitGib     pgtype.Int4 `json:"space_limit_gib"`
	Priority          pgtype.Int4 `json:"priority"`
	HealthStatus      pgtype.Text `json:"health_status"`
}

func (q *Queries) CreateReplica(ctx context.Context, arg CreateReplicaParams) (DriveReplica, error) {
	row := q.db.QueryRow(ctx, createReplica,
		arg.ServiceAccountID,
		arg.Name,
		arg.SharedDriveID,
		arg.StreamingFolderID,
		arg.GemdriveFolderID,
		arg.RecoveryFolderID,
		arg.SpaceLimitGib,
		arg.Priority,
		arg.HealthStatus,
	)
	var i DriveReplica
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.Name,
		&i.SharedDriveID,
		&i.StreamingFolderID,
		&i.GemdriveFolderID,
		&i.RecoveryFolderID,
		&i.SpaceLimitGib,
		&i.Priority,
		&i.HealthStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReplica = `-- name: DeleteReplica :exec
DELETE FROM drive.replicas
WHERE id = $1
`

func (q *Queries) DeleteReplica(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReplica, id)
	return err
}

const listReplicas = `-- name: ListReplicas :many
SELECT 
    r.id, r.service_account_id, r.name, r.shared_drive_id, r.streaming_folder_id, r.gemdrive_folder_id, r.recovery_folder_id, r.space_limit_gib, r.priority, r.health_status, r.created_at, r.updated_at,
    sa.email as service_account_email
FROM drive.replicas r
LEFT JOIN drive.service_accounts sa ON r.service_account_id = sa.id
ORDER BY r.priority DESC, r.created_at ASC
`

type ListReplicasRow struct {
	ID                  int64              `json:"id"`
	ServiceAccountID    pgtype.Int8        `json:"service_account_id"`
	Name                string             `json:"name"`
	SharedDriveID       string             `json:"shared_drive_id"`
	StreamingFolderID   pgtype.Text        `json:"streaming_folder_id"`
	GemdriveFolderID    pgtype.Text        `json:"gemdrive_folder_id"`
	RecoveryFolderID    pgtype.Text        `json:"recovery_folder_id"`
	SpaceLimitGib       pgtype.Int4        `json:"space_limit_gib"`
	Priority            pgtype.Int4        `json:"priority"`
	HealthStatus        pgtype.Text        `json:"health_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ServiceAccountEmail pgtype.Text        `json:"service_account_email"`
}

func (q *Queries) ListReplicas(ctx context.Context) ([]ListReplicasRow, error) {
	rows, err := q.db.Query(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplicasRow
	for rows.Next() {
		var i ListReplicasRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceAccountID,
			&i.Name,
			&i.SharedDriveID,
			&i.StreamingFolderID,
			&i.GemdriveFolderID,
			&i.RecoveryFolderID,
			&i.SpaceLimitGib,
			&i.Priority,
			&i.HealthStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceAccountEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReplicaStatus = `-- name: UpdateReplicaStatus :exec
UPDATE drive.replicas
SET health_status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateReplicaStatusParams struct {
	HealthStatus pgtype.Text `json:"health_status"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateReplicaStatus(ctx context.Context, arg UpdateReplicaStatusParams) error {
	_, err := q.db.Exec(ctx, updateReplicaStatus, arg.HealthStatus, arg.ID)
	return err
}
