// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT value FROM app_settings WHERE key = $1 LIMIT 1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value FROM app_settings
`

type ListAppSettingsRow struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) ListAppSettings(ctx context.Context) ([]ListAppSettingsRow, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppSettingsRow
	for rows.Next() {
		var i ListAppSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppSetting = `-- name: UpdateAppSetting :exec
INSERT INTO app_settings (key, value, updated_at) 
VALUES ($1, $2, NOW()) 
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type UpdateAppSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpdateAppSetting(ctx context.Context, arg UpdateAppSettingParams) error {
	_, err := q.db.Exec(ctx, updateAppSetting, arg.Key, arg.Value)
	return err
}
