// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countShopItems = `-- name: CountShopItems :one
SELECT COUNT(*) FROM shop_items
`

func (q *Queries) CountShopItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countShopItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShopItem = `-- name: CreateShopItem :one
INSERT INTO shop_items (
    name, description, type, collection, price, media_id, meta, preview_css, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, description, type, collection, price, media_id, meta, preview_css, is_active, created_at, updated_at
`

type CreateShopItemParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Collection  pgtype.Text `json:"collection"`
	Price       int64       `json:"price"`
	MediaID     pgtype.Int8 `json:"media_id"`
	Meta        []byte      `json:"meta"`
	PreviewCss  pgtype.Text `json:"preview_css"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateShopItem(ctx context.Context, arg CreateShopItemParams) (ShopItem, error) {
	row := q.db.QueryRow(ctx, createShopItem,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Collection,
		arg.Price,
		arg.MediaID,
		arg.Meta,
		arg.PreviewCss,
		arg.IsActive,
	)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Collection,
		&i.Price,
		&i.MediaID,
		&i.Meta,
		&i.PreviewCss,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserInventoryItem = `-- name: CreateUserInventoryItem :one
INSERT INTO user_inventory (
    user_id, shop_item_id, purchased_at
) VALUES (
    $1, $2, NOW()
) RETURNING id, user_id, shop_item_id, equipped_by_profile_id, purchased_at
`

type CreateUserInventoryItemParams struct {
	UserID     int64 `json:"user_id"`
	ShopItemID int64 `json:"shop_item_id"`
}

func (q *Queries) CreateUserInventoryItem(ctx context.Context, arg CreateUserInventoryItemParams) (UserInventory, error) {
	row := q.db.QueryRow(ctx, createUserInventoryItem, arg.UserID, arg.ShopItemID)
	var i UserInventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopItemID,
		&i.EquippedByProfileID,
		&i.PurchasedAt,
	)
	return i, err
}

const deleteShopItem = `-- name: DeleteShopItem :exec
DELETE FROM shop_items WHERE id = $1
`

func (q *Queries) DeleteShopItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteShopItem, id)
	return err
}

const equipShopItemToProfile = `-- name: EquipShopItemToProfile :exec
UPDATE user_inventory
SET equipped_by_profile_id = $1
WHERE user_id = $2 AND id = $3
`

type EquipShopItemToProfileParams struct {
	EquippedByProfileID pgtype.Int8 `json:"equipped_by_profile_id"`
	UserID              int64       `json:"user_id"`
	ID                  int64       `json:"id"`
}

func (q *Queries) EquipShopItemToProfile(ctx context.Context, arg EquipShopItemToProfileParams) error {
	_, err := q.db.Exec(ctx, equipShopItemToProfile, arg.EquippedByProfileID, arg.UserID, arg.ID)
	return err
}

const getShopItem = `-- name: GetShopItem :one
SELECT id, name, description, type, collection, price, media_id, meta, preview_css, is_active, created_at, updated_at FROM shop_items WHERE id = $1
`

func (q *Queries) GetShopItem(ctx context.Context, id int64) (ShopItem, error) {
	row := q.db.QueryRow(ctx, getShopItem, id)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Collection,
		&i.Price,
		&i.MediaID,
		&i.Meta,
		&i.PreviewCss,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInventory = `-- name: GetUserInventory :many
SELECT ui.id, ui.user_id, ui.shop_item_id, ui.equipped_by_profile_id, ui.purchased_at, si.name, si.type, si.meta, si.preview_css
FROM user_inventory ui
JOIN shop_items si ON ui.shop_item_id = si.id
WHERE ui.user_id = $1
`

type GetUserInventoryRow struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	ShopItemID          int64              `json:"shop_item_id"`
	EquippedByProfileID pgtype.Int8        `json:"equipped_by_profile_id"`
	PurchasedAt         pgtype.Timestamptz `json:"purchased_at"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Meta                []byte             `json:"meta"`
	PreviewCss          pgtype.Text        `json:"preview_css"`
}

func (q *Queries) GetUserInventory(ctx context.Context, userID int64) ([]GetUserInventoryRow, error) {
	rows, err := q.db.Query(ctx, getUserInventory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInventoryRow
	for rows.Next() {
		var i GetUserInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopItemID,
			&i.EquippedByProfileID,
			&i.PurchasedAt,
			&i.Name,
			&i.Type,
			&i.Meta,
			&i.PreviewCss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopItems = `-- name: ListShopItems :many
SELECT id, name, description, type, collection, price, media_id, meta, preview_css, is_active, created_at, updated_at FROM shop_items
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListShopItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShopItems(ctx context.Context, arg ListShopItemsParams) ([]ShopItem, error) {
	rows, err := q.db.Query(ctx, listShopItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopItem
	for rows.Next() {
		var i ShopItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Collection,
			&i.Price,
			&i.MediaID,
			&i.Meta,
			&i.PreviewCss,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unequipShopItemTypeFromProfile = `-- name: UnequipShopItemTypeFromProfile :exec
UPDATE user_inventory ui
SET equipped_by_profile_id = NULL
FROM shop_items si
WHERE ui.shop_item_id = si.id 
  AND ui.user_id = $1 
  AND ui.equipped_by_profile_id = $2
  AND si.type = $3
`

type UnequipShopItemTypeFromProfileParams struct {
	UserID              int64       `json:"user_id"`
	EquippedByProfileID pgtype.Int8 `json:"equipped_by_profile_id"`
	Type                string      `json:"type"`
}

func (q *Queries) UnequipShopItemTypeFromProfile(ctx context.Context, arg UnequipShopItemTypeFromProfileParams) error {
	_, err := q.db.Exec(ctx, unequipShopItemTypeFromProfile, arg.UserID, arg.EquippedByProfileID, arg.Type)
	return err
}

const updateShopItem = `-- name: UpdateShopItem :one
UPDATE shop_items
SET 
    name = coalesce($1, name),
    description = coalesce($2, description),
    type = coalesce($3, type),
    collection = coalesce($4, collection),
    price = coalesce($5, price),
    media_id = coalesce($6, media_id),
    meta = coalesce($7, meta),
    preview_css = coalesce($8, preview_css),
    is_active = coalesce($9, is_active),
    updated_at = NOW()
WHERE id = $10
RETURNING id, name, description, type, collection, price, media_id, meta, preview_css, is_active, created_at, updated_at
`

type UpdateShopItemParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Type        pgtype.Text `json:"type"`
	Collection  pgtype.Text `json:"collection"`
	Price       pgtype.Int8 `json:"price"`
	MediaID     pgtype.Int8 `json:"media_id"`
	Meta        []byte      `json:"meta"`
	PreviewCss  pgtype.Text `json:"preview_css"`
	IsActive    pgtype.Bool `json:"is_active"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateShopItem(ctx context.Context, arg UpdateShopItemParams) (ShopItem, error) {
	row := q.db.QueryRow(ctx, updateShopItem,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Collection,
		arg.Price,
		arg.MediaID,
		arg.Meta,
		arg.PreviewCss,
		arg.IsActive,
		arg.ID,
	)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Collection,
		&i.Price,
		&i.MediaID,
		&i.Meta,
		&i.PreviewCss,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
