// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tmdb_sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMovieFullDetails = `-- name: GetMovieFullDetails :one

SELECT 
    m.id, m.uuid, m.slug, m.tmdb_id, m.tvdb_id, m.imdb_id, m.is_type, m.original_name, m.title_lat, m.title_esp, m.title_eng, m.overview, m.trailer_key, m.release_date, m.runtime, m.poster_path, m.poster_path_tv, m.backdrop_path, m.logo_path, m.certification, m.vote_average, m.vote_count, m.vote_gf, m.views, m.premiere, m.upcoming, m.premium, m.active, m.enable_stream, m.enable_download, m.enable_ads_unlock, m.search_vector, m.created_at, m.updated_at,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', g.id, 'name', g.name_eng))
         FROM movie_genres mg JOIN genres g ON mg.genre_id = g.id
         WHERE mg.movie_id = m.id), '[]'::jsonb
    ) AS genres,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'id', c.id, 'name', c.name, 'profile_path', c.profile_path, 
            'character_name', mc.character_name, 'job', mc.job
         ) ORDER BY mc.sort_order)
         FROM movie_casts mc JOIN casts c ON mc.cast_id = c.id
         WHERE mc.movie_id = m.id), '[]'::jsonb
    ) AS casts_data,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', n.id, 'name', n.name, 'logo_path', n.poster_path))
         FROM movie_networks mn JOIN networks n ON mn.network_id = n.id
         WHERE mn.movie_id = m.id), '[]'::jsonb
    ) AS networks,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name, 'iso_3166_1', c.iso_3166_1))
         FROM movie_countries mc JOIN countries c ON mc.country_id = c.id
         WHERE mc.movie_id = m.id), '[]'::jsonb
    ) AS countries,
    COALESCE(
        (SELECT to_jsonb(col)
         FROM movie_collections mcol JOIN collections col ON mcol.collection_id = col.id
         WHERE mcol.movie_id = m.id LIMIT 1
        ), 'null'::jsonb
    ) AS collection,
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = m.id AND type = 'poster' AND is_main = true LIMIT 1), '') AS main_poster,
    COALESCE((SELECT file_path FROM media_images WHERE movie_id = m.id AND type IN ('backdrop', 'tvthumb') AND is_main = true LIMIT 1), '') AS main_backdrop,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', id, 'file_path', file_path, 'type', type, 'source', source, 'is_main', is_main))
         FROM media_images
         WHERE movie_id = m.id), '[]'::jsonb
    ) AS images
FROM movies m
WHERE m.id = $1
`

type GetMovieFullDetailsRow struct {
	ID              int64              `json:"id"`
	Uuid            pgtype.UUID        `json:"uuid"`
	Slug            string             `json:"slug"`
	TmdbID          pgtype.Int8        `json:"tmdb_id"`
	TvdbID          pgtype.Int8        `json:"tvdb_id"`
	ImdbID          pgtype.Text        `json:"imdb_id"`
	IsType          string             `json:"is_type"`
	OriginalName    string             `json:"original_name"`
	TitleLat        pgtype.Text        `json:"title_lat"`
	TitleEsp        pgtype.Text        `json:"title_esp"`
	TitleEng        pgtype.Text        `json:"title_eng"`
	Overview        pgtype.Text        `json:"overview"`
	TrailerKey      pgtype.Text        `json:"trailer_key"`
	ReleaseDate     pgtype.Date        `json:"release_date"`
	Runtime         pgtype.Int2        `json:"runtime"`
	PosterPath      pgtype.Text        `json:"poster_path"`
	PosterPathTv    pgtype.Text        `json:"poster_path_tv"`
	BackdropPath    pgtype.Text        `json:"backdrop_path"`
	LogoPath        pgtype.Text        `json:"logo_path"`
	Certification   pgtype.Text        `json:"certification"`
	VoteAverage     pgtype.Numeric     `json:"vote_average"`
	VoteCount       int64              `json:"vote_count"`
	VoteGf          int64              `json:"vote_gf"`
	Views           int64              `json:"views"`
	Premiere        bool               `json:"premiere"`
	Upcoming        bool               `json:"upcoming"`
	Premium         bool               `json:"premium"`
	Active          bool               `json:"active"`
	EnableStream    bool               `json:"enable_stream"`
	EnableDownload  bool               `json:"enable_download"`
	EnableAdsUnlock bool               `json:"enable_ads_unlock"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Genres          interface{}        `json:"genres"`
	CastsData       interface{}        `json:"casts_data"`
	Networks        interface{}        `json:"networks"`
	Countries       interface{}        `json:"countries"`
	Collection      interface{}        `json:"collection"`
	MainPoster      interface{}        `json:"main_poster"`
	MainBackdrop    interface{}        `json:"main_backdrop"`
	Images          interface{}        `json:"images"`
}

// ==========================================
// GET DETAILS WITH RELATIONS (For Editing)
// ==========================================
func (q *Queries) GetMovieFullDetails(ctx context.Context, id int64) (GetMovieFullDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMovieFullDetails, id)
	var i GetMovieFullDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.TmdbID,
		&i.TvdbID,
		&i.ImdbID,
		&i.IsType,
		&i.OriginalName,
		&i.TitleLat,
		&i.TitleEsp,
		&i.TitleEng,
		&i.Overview,
		&i.TrailerKey,
		&i.ReleaseDate,
		&i.Runtime,
		&i.PosterPath,
		&i.PosterPathTv,
		&i.BackdropPath,
		&i.LogoPath,
		&i.Certification,
		&i.VoteAverage,
		&i.VoteCount,
		&i.VoteGf,
		&i.Views,
		&i.Premiere,
		&i.Upcoming,
		&i.Premium,
		&i.Active,
		&i.EnableStream,
		&i.EnableDownload,
		&i.EnableAdsUnlock,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Genres,
		&i.CastsData,
		&i.Networks,
		&i.Countries,
		&i.Collection,
		&i.MainPoster,
		&i.MainBackdrop,
		&i.Images,
	)
	return i, err
}

const getSerieFullDetails = `-- name: GetSerieFullDetails :one
SELECT 
    s.id, s.uuid, s.slug, s.tmdb_id, s.tvdb_id, s.imdb_id, s.is_type, s.original_name, s.title_lat, s.title_esp, s.title_eng, s.overview, s.trailer_key, s.first_air_date, s.episode_run_time, s.poster_path, s.poster_path_tv, s.backdrop_path, s.logo_path, s.certification, s.vote_average, s.vote_count, s.vote_gf, s.views, s.premiere, s.upcoming, s.premium, s.active, s.search_vector, s.created_at, s.updated_at,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', g.id, 'name', g.name_eng))
         FROM serie_genres sg JOIN genres g ON sg.genre_id = g.id
         WHERE sg.serie_id = s.id), '[]'::jsonb
    ) AS genres,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'id', c.id, 'name', c.name, 'profile_path', c.profile_path, 
            'character_name', sc.character_name, 'job', sc.job
         ) ORDER BY sc.sort_order)
         FROM serie_casts sc JOIN casts c ON sc.cast_id = c.id
         WHERE sc.serie_id = s.id), '[]'::jsonb
    ) AS casts_data,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', n.id, 'name', n.name, 'logo_path', n.poster_path))
         FROM serie_networks sn JOIN networks n ON sn.network_id = n.id
         WHERE sn.serie_id = s.id), '[]'::jsonb
    ) AS networks,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name, 'iso_3166_1', c.iso_3166_1))
         FROM serie_countries sc JOIN countries c ON sc.country_id = c.id
         WHERE sc.serie_id = s.id), '[]'::jsonb
    ) AS countries,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = s.id AND type = 'poster' AND is_main = true LIMIT 1), '') AS main_poster,
    COALESCE((SELECT file_path FROM media_images WHERE serie_id = s.id AND type IN ('backdrop', 'tvthumb') AND is_main = true LIMIT 1), '') AS main_backdrop,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('id', id, 'file_path', file_path, 'type', type, 'source', source, 'is_main', is_main))
         FROM media_images
         WHERE serie_id = s.id), '[]'::jsonb
    ) AS images
FROM series s
WHERE s.id = $1
`

type GetSerieFullDetailsRow struct {
	ID             int64              `json:"id"`
	Uuid           pgtype.UUID        `json:"uuid"`
	Slug           string             `json:"slug"`
	TmdbID         pgtype.Int8        `json:"tmdb_id"`
	TvdbID         pgtype.Int8        `json:"tvdb_id"`
	ImdbID         pgtype.Text        `json:"imdb_id"`
	IsType         string             `json:"is_type"`
	OriginalName   string             `json:"original_name"`
	TitleLat       pgtype.Text        `json:"title_lat"`
	TitleEsp       pgtype.Text        `json:"title_esp"`
	TitleEng       pgtype.Text        `json:"title_eng"`
	Overview       pgtype.Text        `json:"overview"`
	TrailerKey     pgtype.Text        `json:"trailer_key"`
	FirstAirDate   pgtype.Date        `json:"first_air_date"`
	EpisodeRunTime pgtype.Int2        `json:"episode_run_time"`
	PosterPath     pgtype.Text        `json:"poster_path"`
	PosterPathTv   pgtype.Text        `json:"poster_path_tv"`
	BackdropPath   pgtype.Text        `json:"backdrop_path"`
	LogoPath       pgtype.Text        `json:"logo_path"`
	Certification  pgtype.Text        `json:"certification"`
	VoteAverage    pgtype.Numeric     `json:"vote_average"`
	VoteCount      int64              `json:"vote_count"`
	VoteGf         int64              `json:"vote_gf"`
	Views          int64              `json:"views"`
	Premiere       bool               `json:"premiere"`
	Upcoming       bool               `json:"upcoming"`
	Premium        bool               `json:"premium"`
	Active         bool               `json:"active"`
	SearchVector   interface{}        `json:"search_vector"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Genres         interface{}        `json:"genres"`
	CastsData      interface{}        `json:"casts_data"`
	Networks       interface{}        `json:"networks"`
	Countries      interface{}        `json:"countries"`
	MainPoster     interface{}        `json:"main_poster"`
	MainBackdrop   interface{}        `json:"main_backdrop"`
	Images         interface{}        `json:"images"`
}

func (q *Queries) GetSerieFullDetails(ctx context.Context, id int64) (GetSerieFullDetailsRow, error) {
	row := q.db.QueryRow(ctx, getSerieFullDetails, id)
	var i GetSerieFullDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.TmdbID,
		&i.TvdbID,
		&i.ImdbID,
		&i.IsType,
		&i.OriginalName,
		&i.TitleLat,
		&i.TitleEsp,
		&i.TitleEng,
		&i.Overview,
		&i.TrailerKey,
		&i.FirstAirDate,
		&i.EpisodeRunTime,
		&i.PosterPath,
		&i.PosterPathTv,
		&i.BackdropPath,
		&i.LogoPath,
		&i.Certification,
		&i.VoteAverage,
		&i.VoteCount,
		&i.VoteGf,
		&i.Views,
		&i.Premiere,
		&i.Upcoming,
		&i.Premium,
		&i.Active,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Genres,
		&i.CastsData,
		&i.Networks,
		&i.Countries,
		&i.MainPoster,
		&i.MainBackdrop,
		&i.Images,
	)
	return i, err
}

const insertMovieCast = `-- name: InsertMovieCast :exec
INSERT INTO movie_casts (movie_id, cast_id, character_name, job, sort_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (movie_id, cast_id) DO NOTHING
`

type InsertMovieCastParams struct {
	MovieID       int64       `json:"movie_id"`
	CastID        int64       `json:"cast_id"`
	CharacterName pgtype.Text `json:"character_name"`
	Job           pgtype.Text `json:"job"`
	SortOrder     int16       `json:"sort_order"`
}

func (q *Queries) InsertMovieCast(ctx context.Context, arg InsertMovieCastParams) error {
	_, err := q.db.Exec(ctx, insertMovieCast,
		arg.MovieID,
		arg.CastID,
		arg.CharacterName,
		arg.Job,
		arg.SortOrder,
	)
	return err
}

const insertMovieCollection = `-- name: InsertMovieCollection :exec
INSERT INTO movie_collections (movie_id, collection_id)
VALUES ($1, $2)
ON CONFLICT (movie_id, collection_id) DO NOTHING
`

type InsertMovieCollectionParams struct {
	MovieID      int64 `json:"movie_id"`
	CollectionID int64 `json:"collection_id"`
}

func (q *Queries) InsertMovieCollection(ctx context.Context, arg InsertMovieCollectionParams) error {
	_, err := q.db.Exec(ctx, insertMovieCollection, arg.MovieID, arg.CollectionID)
	return err
}

const insertMovieCountry = `-- name: InsertMovieCountry :exec
INSERT INTO movie_countries (movie_id, country_id) 
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMovieCountryParams struct {
	MovieID   int64 `json:"movie_id"`
	CountryID int64 `json:"country_id"`
}

func (q *Queries) InsertMovieCountry(ctx context.Context, arg InsertMovieCountryParams) error {
	_, err := q.db.Exec(ctx, insertMovieCountry, arg.MovieID, arg.CountryID)
	return err
}

const insertMovieGenre = `-- name: InsertMovieGenre :exec
INSERT INTO movie_genres (movie_id, genre_id)
VALUES ($1, $2)
ON CONFLICT (movie_id, genre_id) DO NOTHING
`

type InsertMovieGenreParams struct {
	MovieID int64 `json:"movie_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) InsertMovieGenre(ctx context.Context, arg InsertMovieGenreParams) error {
	_, err := q.db.Exec(ctx, insertMovieGenre, arg.MovieID, arg.GenreID)
	return err
}

const insertMovieNetwork = `-- name: InsertMovieNetwork :exec
INSERT INTO movie_networks (movie_id, network_id)
VALUES ($1, $2)
ON CONFLICT (movie_id, network_id) DO NOTHING
`

type InsertMovieNetworkParams struct {
	MovieID   int64 `json:"movie_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) InsertMovieNetwork(ctx context.Context, arg InsertMovieNetworkParams) error {
	_, err := q.db.Exec(ctx, insertMovieNetwork, arg.MovieID, arg.NetworkID)
	return err
}

const insertSerieCast = `-- name: InsertSerieCast :exec
INSERT INTO serie_casts (serie_id, cast_id, character_name, job, sort_order)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (serie_id, cast_id) DO NOTHING
`

type InsertSerieCastParams struct {
	SerieID       int64       `json:"serie_id"`
	CastID        int64       `json:"cast_id"`
	CharacterName pgtype.Text `json:"character_name"`
	Job           pgtype.Text `json:"job"`
	SortOrder     int16       `json:"sort_order"`
}

func (q *Queries) InsertSerieCast(ctx context.Context, arg InsertSerieCastParams) error {
	_, err := q.db.Exec(ctx, insertSerieCast,
		arg.SerieID,
		arg.CastID,
		arg.CharacterName,
		arg.Job,
		arg.SortOrder,
	)
	return err
}

const insertSerieCountry = `-- name: InsertSerieCountry :exec
INSERT INTO serie_countries (serie_id, country_id) 
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSerieCountryParams struct {
	SerieID   int64 `json:"serie_id"`
	CountryID int64 `json:"country_id"`
}

func (q *Queries) InsertSerieCountry(ctx context.Context, arg InsertSerieCountryParams) error {
	_, err := q.db.Exec(ctx, insertSerieCountry, arg.SerieID, arg.CountryID)
	return err
}

const insertSerieGenre = `-- name: InsertSerieGenre :exec
INSERT INTO serie_genres (serie_id, genre_id)
VALUES ($1, $2)
ON CONFLICT (serie_id, genre_id) DO NOTHING
`

type InsertSerieGenreParams struct {
	SerieID int64 `json:"serie_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) InsertSerieGenre(ctx context.Context, arg InsertSerieGenreParams) error {
	_, err := q.db.Exec(ctx, insertSerieGenre, arg.SerieID, arg.GenreID)
	return err
}

const insertSerieNetwork = `-- name: InsertSerieNetwork :exec
INSERT INTO serie_networks (serie_id, network_id)
VALUES ($1, $2)
ON CONFLICT (serie_id, network_id) DO NOTHING
`

type InsertSerieNetworkParams struct {
	SerieID   int64 `json:"serie_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) InsertSerieNetwork(ctx context.Context, arg InsertSerieNetworkParams) error {
	_, err := q.db.Exec(ctx, insertSerieNetwork, arg.SerieID, arg.NetworkID)
	return err
}

const updateCastDetails = `-- name: UpdateCastDetails :exec
UPDATE casts SET
    place_of_birth = COALESCE($2, place_of_birth),
    imdb_id = COALESCE($3, imdb_id),
    biography = COALESCE($4, biography),
    adult = COALESCE($5, adult),
    birthday = COALESCE($6, birthday),
    deathday = COALESCE($7, deathday)
WHERE tmdb_id = $1
`

type UpdateCastDetailsParams struct {
	TmdbID       pgtype.Int8 `json:"tmdb_id"`
	PlaceOfBirth pgtype.Text `json:"place_of_birth"`
	ImdbID       pgtype.Text `json:"imdb_id"`
	Biography    pgtype.Text `json:"biography"`
	Adult        bool        `json:"adult"`
	Birthday     pgtype.Date `json:"birthday"`
	Deathday     pgtype.Date `json:"deathday"`
}

func (q *Queries) UpdateCastDetails(ctx context.Context, arg UpdateCastDetailsParams) error {
	_, err := q.db.Exec(ctx, updateCastDetails,
		arg.TmdbID,
		arg.PlaceOfBirth,
		arg.ImdbID,
		arg.Biography,
		arg.Adult,
		arg.Birthday,
		arg.Deathday,
	)
	return err
}

const updateCollectionDetails = `-- name: UpdateCollectionDetails :exec
UPDATE collections SET
    name_lat = COALESCE($2, name_lat),
    name_esp = COALESCE($3, name_esp),
    name_eng = COALESCE($4, name_eng),
    overview = COALESCE($5, overview),
    backdrop_path = COALESCE($6, backdrop_path),
    slug = COALESCE($7, slug)
WHERE tmdb_id = $1
`

type UpdateCollectionDetailsParams struct {
	TmdbID       pgtype.Int8 `json:"tmdb_id"`
	NameLat      pgtype.Text `json:"name_lat"`
	NameEsp      pgtype.Text `json:"name_esp"`
	NameEng      pgtype.Text `json:"name_eng"`
	Overview     pgtype.Text `json:"overview"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

func (q *Queries) UpdateCollectionDetails(ctx context.Context, arg UpdateCollectionDetailsParams) error {
	_, err := q.db.Exec(ctx, updateCollectionDetails,
		arg.TmdbID,
		arg.NameLat,
		arg.NameEsp,
		arg.NameEng,
		arg.Overview,
		arg.BackdropPath,
		arg.Slug,
	)
	return err
}

const upsertCast = `-- name: UpsertCast :one

INSERT INTO casts (
    tmdb_id, name, original_name, gender, profile_path, place_of_birth, imdb_id, known_for_department, biography, adult, birthday, deathday
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (tmdb_id) DO UPDATE SET
    name = EXCLUDED.name,
    original_name = EXCLUDED.original_name,
    gender = EXCLUDED.gender,
    profile_path = EXCLUDED.profile_path,
    place_of_birth = EXCLUDED.place_of_birth,
    imdb_id = EXCLUDED.imdb_id,
    known_for_department = EXCLUDED.known_for_department,
    biography = EXCLUDED.biography,
    adult = EXCLUDED.adult,
    birthday = EXCLUDED.birthday,
    deathday = EXCLUDED.deathday
RETURNING id
`

type UpsertCastParams struct {
	TmdbID             pgtype.Int8 `json:"tmdb_id"`
	Name               string      `json:"name"`
	OriginalName       pgtype.Text `json:"original_name"`
	Gender             pgtype.Int2 `json:"gender"`
	ProfilePath        pgtype.Text `json:"profile_path"`
	PlaceOfBirth       pgtype.Text `json:"place_of_birth"`
	ImdbID             pgtype.Text `json:"imdb_id"`
	KnownForDepartment pgtype.Text `json:"known_for_department"`
	Biography          pgtype.Text `json:"biography"`
	Adult              bool        `json:"adult"`
	Birthday           pgtype.Date `json:"birthday"`
	Deathday           pgtype.Date `json:"deathday"`
}

// ==========================================
// CASTS
// ==========================================
func (q *Queries) UpsertCast(ctx context.Context, arg UpsertCastParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertCast,
		arg.TmdbID,
		arg.Name,
		arg.OriginalName,
		arg.Gender,
		arg.ProfilePath,
		arg.PlaceOfBirth,
		arg.ImdbID,
		arg.KnownForDepartment,
		arg.Biography,
		arg.Adult,
		arg.Birthday,
		arg.Deathday,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCollection = `-- name: UpsertCollection :one

INSERT INTO collections (tmdb_id, original_name, name_lat, name_esp, name_eng, overview, poster_path, backdrop_path, slug)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tmdb_id) DO UPDATE SET
    original_name = EXCLUDED.original_name,
    name_lat = EXCLUDED.name_lat,
    name_esp = EXCLUDED.name_esp,
    name_eng = EXCLUDED.name_eng,
    overview = EXCLUDED.overview,
    poster_path = EXCLUDED.poster_path,
    backdrop_path = EXCLUDED.backdrop_path,
    slug = EXCLUDED.slug
RETURNING id
`

type UpsertCollectionParams struct {
	TmdbID       pgtype.Int8 `json:"tmdb_id"`
	OriginalName string      `json:"original_name"`
	NameLat      pgtype.Text `json:"name_lat"`
	NameEsp      pgtype.Text `json:"name_esp"`
	NameEng      pgtype.Text `json:"name_eng"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
	Slug         string      `json:"slug"`
}

// ==========================================
// COLLECTIONS
// ==========================================
func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertCollection,
		arg.TmdbID,
		arg.OriginalName,
		arg.NameLat,
		arg.NameEsp,
		arg.NameEng,
		arg.Overview,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Slug,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCountry = `-- name: UpsertCountry :one

INSERT INTO countries (
    name, english_name, iso_3166_1
) VALUES (
    $1, $2, $3
)
ON CONFLICT (iso_3166_1) DO UPDATE SET
    name = EXCLUDED.name,
    english_name = EXCLUDED.english_name
RETURNING id
`

type UpsertCountryParams struct {
	Name        string      `json:"name"`
	EnglishName pgtype.Text `json:"english_name"`
	Iso31661    string      `json:"iso_3166_1"`
}

// ==========================================
// COUNTRIES
// ==========================================
func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertCountry, arg.Name, arg.EnglishName, arg.Iso31661)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertGenre = `-- name: UpsertGenre :one

INSERT INTO genres (tmdb_id, name_eng, name_esp, slug, image_path)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tmdb_id) DO UPDATE SET
    name_eng = EXCLUDED.name_eng,
    name_esp = EXCLUDED.name_esp,
    slug = EXCLUDED.slug,
    image_path = EXCLUDED.image_path
RETURNING id
`

type UpsertGenreParams struct {
	TmdbID    pgtype.Int8 `json:"tmdb_id"`
	NameEng   string      `json:"name_eng"`
	NameEsp   pgtype.Text `json:"name_esp"`
	Slug      string      `json:"slug"`
	ImagePath pgtype.Text `json:"image_path"`
}

// ==========================================
// GENRES
// ==========================================
func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertGenre,
		arg.TmdbID,
		arg.NameEng,
		arg.NameEsp,
		arg.Slug,
		arg.ImagePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertNetwork = `-- name: UpsertNetwork :one

INSERT INTO networks (tmdb_id, name, slug, poster_path, backdrop_path)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tmdb_id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    poster_path = EXCLUDED.poster_path,
    backdrop_path = EXCLUDED.backdrop_path
RETURNING id
`

type UpsertNetworkParams struct {
	TmdbID       pgtype.Int8 `json:"tmdb_id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	PosterPath   pgtype.Text `json:"poster_path"`
	BackdropPath pgtype.Text `json:"backdrop_path"`
}

// ==========================================
// NETWORKS / PLATFORMS
// ==========================================
func (q *Queries) UpsertNetwork(ctx context.Context, arg UpsertNetworkParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertNetwork,
		arg.TmdbID,
		arg.Name,
		arg.Slug,
		arg.PosterPath,
		arg.BackdropPath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSerieEpisode = `-- name: UpsertSerieEpisode :one
INSERT INTO serie_episodes (
    tmdb_id, season_id, episode_number, name, overview, still_path, vote_average, vote_count, air_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (season_id, episode_number) DO UPDATE SET
    tmdb_id = EXCLUDED.tmdb_id,
    name = EXCLUDED.name,
    overview = EXCLUDED.overview,
    still_path = EXCLUDED.still_path,
    vote_average = EXCLUDED.vote_average,
    vote_count = EXCLUDED.vote_count,
    air_date = EXCLUDED.air_date
RETURNING id
`

type UpsertSerieEpisodeParams struct {
	TmdbID        pgtype.Int8    `json:"tmdb_id"`
	SeasonID      int64          `json:"season_id"`
	EpisodeNumber int16          `json:"episode_number"`
	Name          string         `json:"name"`
	Overview      pgtype.Text    `json:"overview"`
	StillPath     pgtype.Text    `json:"still_path"`
	VoteAverage   pgtype.Numeric `json:"vote_average"`
	VoteCount     int64          `json:"vote_count"`
	AirDate       pgtype.Date    `json:"air_date"`
}

func (q *Queries) UpsertSerieEpisode(ctx context.Context, arg UpsertSerieEpisodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSerieEpisode,
		arg.TmdbID,
		arg.SeasonID,
		arg.EpisodeNumber,
		arg.Name,
		arg.Overview,
		arg.StillPath,
		arg.VoteAverage,
		arg.VoteCount,
		arg.AirDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSerieSeason = `-- name: UpsertSerieSeason :one

INSERT INTO serie_seasons (
    tmdb_id, serie_id, season_number, name, overview, poster_path, air_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (serie_id, season_number) DO UPDATE SET
    tmdb_id = EXCLUDED.tmdb_id,
    name = EXCLUDED.name,
    overview = EXCLUDED.overview,
    poster_path = EXCLUDED.poster_path,
    air_date = EXCLUDED.air_date
RETURNING id
`

type UpsertSerieSeasonParams struct {
	TmdbID       pgtype.Int8 `json:"tmdb_id"`
	SerieID      int64       `json:"serie_id"`
	SeasonNumber int16       `json:"season_number"`
	Name         string      `json:"name"`
	Overview     pgtype.Text `json:"overview"`
	PosterPath   pgtype.Text `json:"poster_path"`
	AirDate      pgtype.Date `json:"air_date"`
}

// ==========================================
// SEASONS & EPISODES
// ==========================================
func (q *Queries) UpsertSerieSeason(ctx context.Context, arg UpsertSerieSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSerieSeason,
		arg.TmdbID,
		arg.SerieID,
		arg.SeasonNumber,
		arg.Name,
		arg.Overview,
		arg.PosterPath,
		arg.AirDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
