// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, balance) VALUES ($1, 0) RETURNING id, user_id, balance, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (
    wallet_id, amount, type, description, reference_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, wallet_id, amount, type, description, reference_id, created_at
`

type CreateWalletTransactionParams struct {
	WalletID    int64       `json:"wallet_id"`
	Amount      int64       `json:"amount"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
	ReferenceID pgtype.Text `json:"reference_id"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.WalletID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.ReferenceID,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, balance, created_at, updated_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, amount, type, description, reference_id, created_at FROM wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets 
SET balance = balance + $1, updated_at = NOW() 
WHERE id = $2 RETURNING id, user_id, balance, created_at, updated_at
`

type UpdateWalletBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
