name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set lower case repository name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir y Push Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LC }}-backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LC }}-frontend:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://api.gemflix.org
            NEXT_PUBLIC_TURNSTILE_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}
            API_INTERNAL_URL=http://backend:8080
